#pragma once

#include <audio/AudioMusicTypes.h>
#include <audio/AudioTypes.h>

#include "common_melodies.h"

namespace musicdemo {

// =============================================================================
// MELODY 2 — Adventure — 16 bars / 64 beats: A | B | A' | C
// =============================================================================

static const pr32::audio::MusicNote sAdventureLeadNotes[] = {
    pr32::audio::makeNote(pr32::audio::INSTR_PULSE_LEAD, pr32::audio::Note::C, 5, E),
    pr32::audio::makeNote(pr32::audio::INSTR_PULSE_LEAD, pr32::audio::Note::D, 5, E),
    pr32::audio::makeNote(pr32::audio::INSTR_PULSE_LEAD, pr32::audio::Note::E, 5, E),
    pr32::audio::makeNote(pr32::audio::INSTR_PULSE_LEAD, pr32::audio::Note::F, 5, E),
    pr32::audio::makeNote(pr32::audio::INSTR_PULSE_LEAD, pr32::audio::Note::G, 5, E),
    pr32::audio::makeNote(pr32::audio::INSTR_PULSE_LEAD, pr32::audio::Note::A, 5, E),
    pr32::audio::makeNote(pr32::audio::INSTR_PULSE_LEAD, pr32::audio::Note::B, 5, E),
    pr32::audio::makeNote(pr32::audio::INSTR_PULSE_LEAD, pr32::audio::Note::C, 6, E),
    pr32::audio::makeNote(pr32::audio::INSTR_PULSE_LEAD, pr32::audio::Note::B, 5, Q),
    pr32::audio::makeNote(pr32::audio::INSTR_PULSE_LEAD, pr32::audio::Note::G, 5, Q),
    pr32::audio::makeNote(pr32::audio::INSTR_PULSE_LEAD, pr32::audio::Note::E, 5, Q),
    pr32::audio::makeNote(pr32::audio::INSTR_PULSE_LEAD, pr32::audio::Note::C, 5, Q),
    pr32::audio::makeRest(Q),
    pr32::audio::makeNote(pr32::audio::INSTR_PULSE_LEAD, pr32::audio::Note::E, 5, Q),
    pr32::audio::makeNote(pr32::audio::INSTR_PULSE_LEAD, pr32::audio::Note::G, 5, Q),
    pr32::audio::makeNote(pr32::audio::INSTR_PULSE_LEAD, pr32::audio::Note::C, 6, Q),
    pr32::audio::makeRest(Q),
    pr32::audio::makeNote(pr32::audio::INSTR_PULSE_LEAD, pr32::audio::Note::F, 5, E),
    pr32::audio::makeRest(S),
    pr32::audio::makeNote(pr32::audio::INSTR_PULSE_LEAD, pr32::audio::Note::F, 5, S),
    pr32::audio::makeNote(pr32::audio::INSTR_PULSE_LEAD, pr32::audio::Note::G, 5, Q),
    pr32::audio::makeNote(pr32::audio::INSTR_PULSE_LEAD, pr32::audio::Note::A, 5, E),
    pr32::audio::makeNote(pr32::audio::INSTR_PULSE_LEAD, pr32::audio::Note::G, 5, E),
    pr32::audio::makeNote(pr32::audio::INSTR_PULSE_LEAD, pr32::audio::Note::F, 5, E),
    pr32::audio::makeNote(pr32::audio::INSTR_PULSE_LEAD, pr32::audio::Note::E, 5, E),
    pr32::audio::makeNote(pr32::audio::INSTR_PULSE_LEAD, pr32::audio::Note::D, 5, Q),
    pr32::audio::makeNote(pr32::audio::INSTR_PULSE_LEAD, pr32::audio::Note::C, 5, Q),
    pr32::audio::makeNote(pr32::audio::INSTR_PULSE_LEAD, pr32::audio::Note::B, 4, E),
    pr32::audio::makeNote(pr32::audio::INSTR_PULSE_LEAD, pr32::audio::Note::G, 4, E),
    pr32::audio::makeNote(pr32::audio::INSTR_PULSE_LEAD, pr32::audio::Note::C, 5, Q),
    pr32::audio::makeNote(pr32::audio::INSTR_PULSE_LEAD, pr32::audio::Note::E, 5, Q),
    pr32::audio::makeNote(pr32::audio::INSTR_PULSE_LEAD, pr32::audio::Note::G, 5, H),
    pr32::audio::makeNote(pr32::audio::INSTR_PULSE_LEAD, pr32::audio::Note::C, 5, E),
    pr32::audio::makeNote(pr32::audio::INSTR_PULSE_LEAD, pr32::audio::Note::E, 5, E),
    pr32::audio::makeNote(pr32::audio::INSTR_PULSE_LEAD, pr32::audio::Note::G, 5, E),
    pr32::audio::makeNote(pr32::audio::INSTR_PULSE_LEAD, pr32::audio::Note::B, 5, E),
    pr32::audio::makeNote(pr32::audio::INSTR_PULSE_LEAD, pr32::audio::Note::D, 5, E),
    pr32::audio::makeNote(pr32::audio::INSTR_PULSE_LEAD, pr32::audio::Note::C, 5, E),
    pr32::audio::makeNote(pr32::audio::INSTR_PULSE_LEAD, pr32::audio::Note::B, 5, E),
    pr32::audio::makeNote(pr32::audio::INSTR_PULSE_LEAD, pr32::audio::Note::G, 5, E),
    pr32::audio::makeNote(pr32::audio::INSTR_PULSE_LEAD, pr32::audio::Note::C, 6, Q),
    pr32::audio::makeNote(pr32::audio::INSTR_PULSE_LEAD, pr32::audio::Note::B, 5, Q),
    pr32::audio::makeNote(pr32::audio::INSTR_PULSE_LEAD, pr32::audio::Note::A, 5, Q),
    pr32::audio::makeNote(pr32::audio::INSTR_PULSE_LEAD, pr32::audio::Note::G, 5, Q),
    pr32::audio::makeNote(pr32::audio::INSTR_PULSE_LEAD, pr32::audio::Note::F, 5, E),
    pr32::audio::makeNote(pr32::audio::INSTR_PULSE_LEAD, pr32::audio::Note::E, 5, E),
    pr32::audio::makeNote(pr32::audio::INSTR_PULSE_LEAD, pr32::audio::Note::D, 5, E),
    pr32::audio::makeNote(pr32::audio::INSTR_PULSE_LEAD, pr32::audio::Note::C, 5, E),
    pr32::audio::makeNote(pr32::audio::INSTR_PULSE_LEAD, pr32::audio::Note::D, 5, Q),
    pr32::audio::makeNote(pr32::audio::INSTR_PULSE_LEAD, pr32::audio::Note::E, 5, Q),
    pr32::audio::makeNote(pr32::audio::INSTR_PULSE_LEAD, pr32::audio::Note::F, 5, Q),
    pr32::audio::makeNote(pr32::audio::INSTR_PULSE_LEAD, pr32::audio::Note::G, 5, Q),
    pr32::audio::makeNote(pr32::audio::INSTR_PULSE_LEAD, pr32::audio::Note::E, 5, Q),
    pr32::audio::makeNote(pr32::audio::INSTR_PULSE_LEAD, pr32::audio::Note::D, 5, Q),
    pr32::audio::makeNote(pr32::audio::INSTR_PULSE_LEAD, pr32::audio::Note::C, 5, H),
    pr32::audio::makeNote(pr32::audio::INSTR_PULSE_LEAD, pr32::audio::Note::G, 4, Q),
    pr32::audio::makeNote(pr32::audio::INSTR_PULSE_LEAD, pr32::audio::Note::A, 4, Q),
    pr32::audio::makeNote(pr32::audio::INSTR_PULSE_LEAD, pr32::audio::Note::B, 4, Q),
    pr32::audio::makeNote(pr32::audio::INSTR_PULSE_LEAD, pr32::audio::Note::C, 5, Q),
    pr32::audio::makeRest(Q),
    pr32::audio::makeNote(pr32::audio::INSTR_PULSE_LEAD, pr32::audio::Note::G, 5, Q),
    pr32::audio::makeNote(pr32::audio::INSTR_PULSE_LEAD, pr32::audio::Note::F, 5, Q),
    pr32::audio::makeNote(pr32::audio::INSTR_PULSE_LEAD, pr32::audio::Note::E, 5, Q),
    pr32::audio::makeNote(pr32::audio::INSTR_PULSE_LEAD, pr32::audio::Note::D, 5, Q),
    pr32::audio::makeNote(pr32::audio::INSTR_PULSE_LEAD, pr32::audio::Note::C, 5, H),
    pr32::audio::makeNote(pr32::audio::INSTR_PULSE_LEAD, pr32::audio::Note::C, 5, Q),
    pr32::audio::makeNote(pr32::audio::INSTR_PULSE_LEAD, pr32::audio::Note::D, 5, Q),
    pr32::audio::makeNote(pr32::audio::INSTR_PULSE_LEAD, pr32::audio::Note::E, 5, Q),
    pr32::audio::makeNote(pr32::audio::INSTR_PULSE_LEAD, pr32::audio::Note::F, 5, Q),
    pr32::audio::makeNote(pr32::audio::INSTR_PULSE_LEAD, pr32::audio::Note::G, 5, Q),
    pr32::audio::makeNote(pr32::audio::INSTR_PULSE_LEAD, pr32::audio::Note::A, 5, Q),
    pr32::audio::makeNote(pr32::audio::INSTR_PULSE_LEAD, pr32::audio::Note::B, 5, Q),
    pr32::audio::makeNote(pr32::audio::INSTR_PULSE_LEAD, pr32::audio::Note::C, 6, Q),
    pr32::audio::makeRest(Q),
    pr32::audio::makeRest(Q),
    pr32::audio::makeRest(Q),
};

static const pr32::audio::MusicNote sAdventureBassNotes[] = {
    pr32::audio::makeNote(DEMO_SNES_BASS_STAC, pr32::audio::Note::C, 2, W),
    pr32::audio::makeNote(DEMO_SNES_BASS_STAC, pr32::audio::Note::G, 2, W),
    pr32::audio::makeNote(DEMO_SNES_BASS_STAC, pr32::audio::Note::A, 2, W),
    pr32::audio::makeNote(DEMO_SNES_BASS_STAC, pr32::audio::Note::F, 2, W),
    pr32::audio::makeNote(DEMO_SNES_BASS_STAC, pr32::audio::Note::C, 2, W),
    pr32::audio::makeNote(DEMO_SNES_BASS_STAC, pr32::audio::Note::G, 2, W),
    pr32::audio::makeNote(DEMO_SNES_BASS_STAC, pr32::audio::Note::A, 2, W),
    pr32::audio::makeNote(DEMO_SNES_BASS_STAC, pr32::audio::Note::F, 2, W),
    pr32::audio::makeNote(DEMO_SNES_BASS_STAC, pr32::audio::Note::C, 2, W),
    pr32::audio::makeNote(DEMO_SNES_BASS_STAC, pr32::audio::Note::G, 2, W),
    pr32::audio::makeNote(DEMO_SNES_BASS_STAC, pr32::audio::Note::A, 2, W),
    pr32::audio::makeNote(DEMO_SNES_BASS_STAC, pr32::audio::Note::F, 2, W),
    pr32::audio::makeNote(DEMO_SNES_BASS_STAC, pr32::audio::Note::C, 2, W),
    pr32::audio::makeNote(DEMO_SNES_BASS_STAC, pr32::audio::Note::G, 2, W),
    pr32::audio::makeNote(DEMO_SNES_BASS_STAC, pr32::audio::Note::A, 2, W),
    pr32::audio::makeNote(DEMO_SNES_BASS_STAC, pr32::audio::Note::F, 2, W),
};

static const pr32::audio::MusicNote sAdventureHarmonyNotes[] = {
    pr32::audio::makeRest(W),
    pr32::audio::makeNote(pr32::audio::INSTR_PULSE_HARMONY, pr32::audio::Note::G, 4, Q),
    pr32::audio::makeRest(Q),
    pr32::audio::makeNote(pr32::audio::INSTR_PULSE_HARMONY, pr32::audio::Note::E, 5, Q),
    pr32::audio::makeRest(W),
    pr32::audio::makeNote(pr32::audio::INSTR_PULSE_HARMONY, pr32::audio::Note::C, 5, Q),
    pr32::audio::makeRest(Q),
    pr32::audio::makeNote(pr32::audio::INSTR_PULSE_HARMONY, pr32::audio::Note::A, 4, Q),
    pr32::audio::makeRest(W),
    pr32::audio::makeNote(pr32::audio::INSTR_PULSE_HARMONY, pr32::audio::Note::G, 4, Q),
    pr32::audio::makeNote(pr32::audio::INSTR_PULSE_HARMONY, pr32::audio::Note::B, 4, Q),
    pr32::audio::makeRest(H),
    pr32::audio::makeNote(pr32::audio::INSTR_PULSE_HARMONY, pr32::audio::Note::E, 4, Q),
    pr32::audio::makeRest(Q),
    pr32::audio::makeNote(pr32::audio::INSTR_PULSE_HARMONY, pr32::audio::Note::G, 4, Q),
    pr32::audio::makeRest(Q),
    pr32::audio::makeRest(W),
    pr32::audio::makeNote(pr32::audio::INSTR_PULSE_HARMONY, pr32::audio::Note::G, 4, Q),
    pr32::audio::makeRest(Q),
    pr32::audio::makeNote(pr32::audio::INSTR_PULSE_HARMONY, pr32::audio::Note::E, 5, Q),
    pr32::audio::makeRest(W),
    pr32::audio::makeNote(pr32::audio::INSTR_PULSE_HARMONY, pr32::audio::Note::C, 5, Q),
    pr32::audio::makeRest(Q),
    pr32::audio::makeNote(pr32::audio::INSTR_PULSE_HARMONY, pr32::audio::Note::A, 4, Q),
    pr32::audio::makeRest(W),
    pr32::audio::makeNote(pr32::audio::INSTR_PULSE_HARMONY, pr32::audio::Note::G, 4, Q),
    pr32::audio::makeNote(pr32::audio::INSTR_PULSE_HARMONY, pr32::audio::Note::B, 4, Q),
    pr32::audio::makeRest(H),
    pr32::audio::makeNote(pr32::audio::INSTR_PULSE_HARMONY, pr32::audio::Note::F, 5, Q),
    pr32::audio::makeRest(Q),
    pr32::audio::makeNote(pr32::audio::INSTR_PULSE_HARMONY, pr32::audio::Note::A, 5, Q),
    pr32::audio::makeRest(Q),
    pr32::audio::makeRest(W),
    pr32::audio::makeNote(pr32::audio::INSTR_PULSE_HARMONY, pr32::audio::Note::G, 4, Q),
    pr32::audio::makeRest(Q),
    pr32::audio::makeNote(pr32::audio::INSTR_PULSE_HARMONY, pr32::audio::Note::E, 5, Q),
    pr32::audio::makeRest(Q),
    pr32::audio::makeRest(Q),
    pr32::audio::makeRest(Q),
    pr32::audio::makeRest(Q),
    pr32::audio::makeRest(Q),
};

static const pr32::audio::MusicNote sAdventureDrumsNotes[] = {
    pr32::audio::makeNote(pr32::audio::INSTR_KICK, pr32::audio::Note::Rest, 1, Q),
    pr32::audio::makeNote(pr32::audio::INSTR_HIHAT, pr32::audio::Note::Rest, 1, Q),
    pr32::audio::makeNote(pr32::audio::INSTR_SNARE, pr32::audio::Note::Rest, 1, Q),
    pr32::audio::makeNote(pr32::audio::INSTR_HIHAT, pr32::audio::Note::Rest, 1, Q),
    pr32::audio::makeNote(pr32::audio::INSTR_HIHAT, pr32::audio::Note::Rest, 1, Q),
    pr32::audio::makeNote(pr32::audio::INSTR_KICK, pr32::audio::Note::Rest, 1, Q),
    pr32::audio::makeNote(pr32::audio::INSTR_SNARE, pr32::audio::Note::Rest, 1, Q),
    pr32::audio::makeNote(pr32::audio::INSTR_HIHAT, pr32::audio::Note::Rest, 1, Q),
    pr32::audio::makeNote(pr32::audio::INSTR_KICK, pr32::audio::Note::Rest, 1, Q),
    pr32::audio::makeNote(pr32::audio::INSTR_HIHAT, pr32::audio::Note::Rest, 1, Q),
    pr32::audio::makeNote(pr32::audio::INSTR_SNARE, pr32::audio::Note::Rest, 1, Q),
    pr32::audio::makeNote(pr32::audio::INSTR_HIHAT, pr32::audio::Note::Rest, 1, Q),
    pr32::audio::makeNote(pr32::audio::INSTR_HIHAT, pr32::audio::Note::Rest, 1, E),
    pr32::audio::makeNote(pr32::audio::INSTR_HIHAT, pr32::audio::Note::Rest, 1, E),
    pr32::audio::makeNote(pr32::audio::INSTR_SNARE, pr32::audio::Note::Rest, 1, Q),
    pr32::audio::makeNote(pr32::audio::INSTR_KICK, pr32::audio::Note::Rest, 1, Q),
    pr32::audio::makeNote(pr32::audio::INSTR_KICK, pr32::audio::Note::Rest, 1, Q),
    pr32::audio::makeNote(pr32::audio::INSTR_HIHAT, pr32::audio::Note::Rest, 1, E),
    pr32::audio::makeNote(pr32::audio::INSTR_SNARE, pr32::audio::Note::Rest, 1, E),
    pr32::audio::makeNote(pr32::audio::INSTR_HIHAT, pr32::audio::Note::Rest, 1, Q),
    pr32::audio::makeNote(pr32::audio::INSTR_HIHAT, pr32::audio::Note::Rest, 1, E),
    pr32::audio::makeRest(E),
    pr32::audio::makeNote(pr32::audio::INSTR_SNARE, pr32::audio::Note::Rest, 1, Q),
    pr32::audio::makeNote(pr32::audio::INSTR_KICK, pr32::audio::Note::Rest, 1, Q),
    pr32::audio::makeNote(pr32::audio::INSTR_KICK, pr32::audio::Note::Rest, 1, Q),
    pr32::audio::makeNote(pr32::audio::INSTR_HIHAT, pr32::audio::Note::Rest, 1, Q),
    pr32::audio::makeNote(pr32::audio::INSTR_SNARE, pr32::audio::Note::Rest, 1, Q),
    pr32::audio::makeNote(pr32::audio::INSTR_HIHAT, pr32::audio::Note::Rest, 1, Q),
    pr32::audio::makeNote(pr32::audio::INSTR_KICK, pr32::audio::Note::Rest, 1, Q),
    pr32::audio::makeNote(pr32::audio::INSTR_SNARE, pr32::audio::Note::Rest, 1, Q),
    pr32::audio::makeNote(pr32::audio::INSTR_HIHAT, pr32::audio::Note::Rest, 1, Q),
    pr32::audio::makeNote(pr32::audio::INSTR_KICK, pr32::audio::Note::Rest, 1, Q),
    pr32::audio::makeNote(pr32::audio::INSTR_HIHAT, pr32::audio::Note::Rest, 1, E),
    pr32::audio::makeNote(pr32::audio::INSTR_SNARE, pr32::audio::Note::Rest, 1, S),
    pr32::audio::makeNote(pr32::audio::INSTR_SNARE, pr32::audio::Note::Rest, 1, S),
    pr32::audio::makeNote(pr32::audio::INSTR_HIHAT, pr32::audio::Note::Rest, 1, E),
    pr32::audio::makeNote(pr32::audio::INSTR_KICK, pr32::audio::Note::Rest, 1, Q),
    pr32::audio::makeNote(pr32::audio::INSTR_HIHAT, pr32::audio::Note::Rest, 1, Q),
    pr32::audio::makeNote(pr32::audio::INSTR_KICK, pr32::audio::Note::Rest, 1, Q),
    pr32::audio::makeNote(pr32::audio::INSTR_HIHAT, pr32::audio::Note::Rest, 1, Q),
    pr32::audio::makeNote(pr32::audio::INSTR_SNARE, pr32::audio::Note::Rest, 1, Q),
    pr32::audio::makeNote(pr32::audio::INSTR_HIHAT, pr32::audio::Note::Rest, 1, Q),
    pr32::audio::makeNote(pr32::audio::INSTR_HIHAT, pr32::audio::Note::Rest, 1, Q),
    pr32::audio::makeNote(pr32::audio::INSTR_KICK, pr32::audio::Note::Rest, 1, Q),
    pr32::audio::makeNote(pr32::audio::INSTR_SNARE, pr32::audio::Note::Rest, 1, Q),
    pr32::audio::makeNote(pr32::audio::INSTR_HIHAT, pr32::audio::Note::Rest, 1, Q),
    pr32::audio::makeNote(pr32::audio::INSTR_KICK, pr32::audio::Note::Rest, 1, Q),
    pr32::audio::makeNote(pr32::audio::INSTR_HIHAT, pr32::audio::Note::Rest, 1, Q),
    pr32::audio::makeNote(pr32::audio::INSTR_SNARE, pr32::audio::Note::Rest, 1, Q),
    pr32::audio::makeNote(pr32::audio::INSTR_HIHAT, pr32::audio::Note::Rest, 1, Q),
    pr32::audio::makeNote(pr32::audio::INSTR_HIHAT, pr32::audio::Note::Rest, 1, E),
    pr32::audio::makeNote(pr32::audio::INSTR_HIHAT, pr32::audio::Note::Rest, 1, E),
    pr32::audio::makeNote(pr32::audio::INSTR_SNARE, pr32::audio::Note::Rest, 1, Q),
    pr32::audio::makeNote(pr32::audio::INSTR_KICK, pr32::audio::Note::Rest, 1, Q),
    pr32::audio::makeNote(pr32::audio::INSTR_KICK, pr32::audio::Note::Rest, 1, Q),
    pr32::audio::makeNote(pr32::audio::INSTR_HIHAT, pr32::audio::Note::Rest, 1, E),
    pr32::audio::makeNote(pr32::audio::INSTR_SNARE, pr32::audio::Note::Rest, 1, E),
    pr32::audio::makeNote(pr32::audio::INSTR_HIHAT, pr32::audio::Note::Rest, 1, Q),
    pr32::audio::makeNote(pr32::audio::INSTR_HIHAT, pr32::audio::Note::Rest, 1, E),
    pr32::audio::makeRest(E),
    pr32::audio::makeNote(pr32::audio::INSTR_SNARE, pr32::audio::Note::Rest, 1, Q),
    pr32::audio::makeNote(pr32::audio::INSTR_KICK, pr32::audio::Note::Rest, 1, Q),
    pr32::audio::makeNote(pr32::audio::INSTR_SNARE, pr32::audio::Note::Rest, 1, E),
    pr32::audio::makeNote(pr32::audio::INSTR_SNARE, pr32::audio::Note::Rest, 1, E),
    pr32::audio::makeNote(pr32::audio::INSTR_KICK, pr32::audio::Note::Rest, 1, Q),
    pr32::audio::makeNote(pr32::audio::INSTR_HIHAT, pr32::audio::Note::Rest, 1, Q),
    pr32::audio::makeNote(pr32::audio::INSTR_KICK, pr32::audio::Note::Rest, 1, Q),
    pr32::audio::makeNote(pr32::audio::INSTR_HIHAT, pr32::audio::Note::Rest, 1, Q),
    pr32::audio::makeNote(pr32::audio::INSTR_SNARE, pr32::audio::Note::Rest, 1, Q),
    pr32::audio::makeNote(pr32::audio::INSTR_HIHAT, pr32::audio::Note::Rest, 1, Q),
    pr32::audio::makeNote(pr32::audio::INSTR_KICK, pr32::audio::Note::Rest, 1, Q),
    pr32::audio::makeNote(pr32::audio::INSTR_HIHAT, pr32::audio::Note::Rest, 1, E),
    pr32::audio::makeNote(pr32::audio::INSTR_HIHAT, pr32::audio::Note::Rest, 1, E),
    pr32::audio::makeNote(pr32::audio::INSTR_SNARE, pr32::audio::Note::Rest, 1, E),
    pr32::audio::makeRest(Q),
};

static const pr32::audio::MusicTrack sAdventureLead = {
    sAdventureLeadNotes,
    sizeof(sAdventureLeadNotes) / sizeof(pr32::audio::MusicNote),
    true,
    pr32::audio::WaveType::PULSE,
    0.5f,
    nullptr,
    nullptr,
    nullptr};

static const pr32::audio::MusicTrack sAdventureBass = {
    sAdventureBassNotes,
    sizeof(sAdventureBassNotes) / sizeof(pr32::audio::MusicNote),
    true,
    pr32::audio::WaveType::TRIANGLE,
    0.5f,
    nullptr,
    nullptr,
    nullptr};

static const pr32::audio::MusicTrack sAdventureHarmony = {
    sAdventureHarmonyNotes,
    sizeof(sAdventureHarmonyNotes) / sizeof(pr32::audio::MusicNote),
    true,
    pr32::audio::WaveType::PULSE,
    0.125f,
    nullptr,
    nullptr,
    nullptr};

static const pr32::audio::MusicTrack sAdventureDrums = {
    sAdventureDrumsNotes,
    sizeof(sAdventureDrumsNotes) / sizeof(pr32::audio::MusicNote),
    true,
    pr32::audio::WaveType::NOISE,
    0.0f,
    nullptr,
    nullptr,
    nullptr};

static const pr32::audio::MusicTrack sAdventureTrack = {
    sAdventureLeadNotes,
    sizeof(sAdventureLeadNotes) / sizeof(pr32::audio::MusicNote),
    true,
    kDemoAdventureLeadWave,
    0.5f,
    &sAdventureBass,
    &sAdventureHarmony,
    &sAdventureDrums};

}
