#ifndef ANIMATEDTILES_H
#define ANIMATEDTILES_H

#include <graphics/Renderer.h>
#include <physics/TileAttributes.h>
#include <stdint.h>
#include <string.h>

// PROGMEM compatibility macros are now provided by Renderer.h

/**
 * PixelRoot32 Exported Scene: AnimatedTiles - Main Scene
 * Generated by PixelRoot32 Tilemap Editor
 */

// Multi-palette mode: palette definitions and PALETTE_MAPPING are in the namespace below

namespace animatedtiles {

    // --- Palette Definitions ---
    // Multi-palette mode: one palette per slot, named after the first layer using that slot

    // Palette for Background (slot 0)
    static const uint16_t PIXELROOT32_SCENE_FLASH_ATTR BACKGROUND_PALETTE[16] = {
        0x0000, // 0: RGB(0, 0, 0) - Transparent
        0x1885, // 1: RGB(31, 16, 42) - blue
        0x498A, // 2: RGB(74, 48, 82) - blue
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000    
    };

    // Palette for Ground (slot 1)
    static const uint16_t PIXELROOT32_SCENE_FLASH_ATTR GROUND_PALETTE[16] = {
        0x0000, // 0: RGB(0, 0, 0) - Transparent
        0x3B2C, // 1: RGB(62, 101, 97) - green
        0x5D2E, // 2: RGB(91, 166, 117) - green
        0x60CA, // 3: RGB(97, 24, 81) - red
        0x6E4D, // 4: RGB(107, 201, 108) - green
        0x6C1F, // 5: RGB(109, 128, 250) - purple
        0x81AA, // 6: RGB(135, 53, 85) - red
        0x81F0, // 7: RGB(135, 62, 132) - red
        0x8DBF, // 8: RGB(141, 183, 255) - purple
        0xA14B, // 9: RGB(163, 40, 88) - red
        0xA2AB, // 10: RGB(166, 85, 95) - red
        0xA433, // 11: RGB(166, 133, 159) - peach/salmon
        0xAF1F, // 12: RGB(174, 226, 255) - purple
        0xCB8E, // 13: RGB(201, 115, 115) - peach/salmon
        0xCA0B, // 14: RGB(204, 66, 94) - red
        0xD376, // 15: RGB(212, 110, 179) - peach/salmon
    };

    // Palette for Details (slot 2)
    static const uint16_t PIXELROOT32_SCENE_FLASH_ATTR DETAILS_PALETTE[16] = {
        0x0000, // 0: RGB(0, 0, 0) - Transparent
        0x60CA, // 1: RGB(97, 24, 81) - red
        0x81AA, // 2: RGB(135, 53, 85) - red
        0xA2AB, // 3: RGB(166, 85, 95) - red
        0xAF1F, // 4: RGB(174, 226, 255) - purple
        0xCB8E, // 5: RGB(201, 115, 115) - peach/salmon
        0xCA0B, // 6: RGB(204, 66, 94) - red
        0xEB0C, // 7: RGB(234, 98, 98) - red
        0xFDCF, // 8: RGB(255, 184, 121) - peach/salmon
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000    
    };

    // Color index mapping for tileset sprites (shared in multi-palette mode)
    static const pixelroot32::graphics::Color PIXELROOT32_SCENE_FLASH_ATTR PALETTE_MAPPING[] = {
        (pixelroot32::graphics::Color)0, // Transparent
        (pixelroot32::graphics::Color)1, // blue
        (pixelroot32::graphics::Color)2, // green
        (pixelroot32::graphics::Color)3, // blue
        (pixelroot32::graphics::Color)4, // green
        (pixelroot32::graphics::Color)5, // red
        (pixelroot32::graphics::Color)6, // green
        (pixelroot32::graphics::Color)7, // purple
        (pixelroot32::graphics::Color)8, // red
        (pixelroot32::graphics::Color)9, // red
        (pixelroot32::graphics::Color)10, // purple
        (pixelroot32::graphics::Color)11, // red
        (pixelroot32::graphics::Color)12, // red
        (pixelroot32::graphics::Color)13, // peach/salmon
        (pixelroot32::graphics::Color)14, // purple
        (pixelroot32::graphics::Color)15 // peach/salmon
    };

    using namespace pixelroot32::physics;

    // --- Tile Dimensions ---
    static const uint8_t TILE_SIZE = 8;
    static const uint8_t MAP_WIDTH = 30;
    static const uint8_t MAP_HEIGHT = 30;

    // --- Layer Definitions ---
    extern pixelroot32::graphics::TileMap4bpp background;
    extern pixelroot32::graphics::TileMap4bpp ground;
    extern pixelroot32::graphics::TileMap4bpp details;

    /**
     * Initializes the scene components. 
     * Call this once before drawing in the render loop.
     */
    void init();


    // ============================================================================
    // PixelRoot32 Tile Behavior Layer (ESP32 Optimization)
    // Generated by PixelRoot32 Tilemap Editor
    // 
    // Data Format:
    // - Dense uint8_t array: 1 byte per tile (O(1) lookup)
    // - Bit flags correspond to TileFlags enum in physics/TileAttributes.h
    // - Stored in flash using PIXELROOT32_SCENE_FLASH_ATTR
    // 
    // Memory Usage: 2700 bytes total
    // ============================================================================

    // --- Behavior Layer: Background (30x30) ---

    /**
     * Dense behavior data array for layer "Background".
     * Each byte contains TileFlags combination for the corresponding tile.
     * 0 = TILE_NONE (no behavior)
     */
    static const uint8_t TILE_BEHAVIOR_LAYER_BACKGROUND[] PIXELROOT32_SCENE_FLASH_ATTR = {
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 0
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 1
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 2
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 3
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 4
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 5
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 6
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 7
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 8
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 9
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 10
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 11
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 12
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 13
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 14
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 15
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 16
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 17
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 18
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 19
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 20
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 21
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 22
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 23
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 24
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 25
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 26
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 27
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 28
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0  // Row 29
    };

    // --- Behavior Layer: Ground (30x30) ---

    /**
     * Dense behavior data array for layer "Ground".
     * Each byte contains TileFlags combination for the corresponding tile.
     * 0 = TILE_NONE (no behavior)
     */
    static const uint8_t TILE_BEHAVIOR_LAYER_GROUND[] PIXELROOT32_SCENE_FLASH_ATTR = {
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 0
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 1
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 2
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 3
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 4
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 5
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 6
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 7
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 8
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 9
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 10
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 11
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 12
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 13
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 14
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 15
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 16
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 17
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 18
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 19
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 20
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 21
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 22
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 23
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 24
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 25
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 26
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 27
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 28
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0  // Row 29
    };

    // --- Behavior Layer: Details (30x30) ---

    /**
     * Dense behavior data array for layer "Details".
     * Each byte contains TileFlags combination for the corresponding tile.
     * 0 = TILE_NONE (no behavior)
     */
    static const uint8_t TILE_BEHAVIOR_LAYER_DETAILS[] PIXELROOT32_SCENE_FLASH_ATTR = {
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 0
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 1
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 2
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 3
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 4
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 5
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 6
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 7
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 8
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 9
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 10
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 11
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 12
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 13
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 14
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 15
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 16
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 17
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 18
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 19
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 20
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 21
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 22
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 23
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 24
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 25
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 26
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 27
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 28
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0  // Row 29
    };


    // All behavior layers
    static const TileBehaviorLayer behavior_layers[] = {
        { TILE_BEHAVIOR_LAYER_BACKGROUND, 30, 30 },         
        { TILE_BEHAVIOR_LAYER_GROUND, 30, 30 },         
        { TILE_BEHAVIOR_LAYER_DETAILS, 30, 30 }    
    };

    static const uint8_t NUM_BEHAVIOR_LAYERS = 3;

    /**
     * Get TileFlags for a specific tile position in a behavior layer.
     * 
     * Args:
     *   layer_idx: Behavior layer index (0-based)
     *   x: X coordinate in tiles
     *   y: Y coordinate in tiles
     * 
     * Returns:
     *   TileFlags combination (0 = TILE_NONE if out of bounds)
     */
    inline uint8_t getTileFlags(uint8_t layer_idx, int x, int y) {
        if (layer_idx >= NUM_BEHAVIOR_LAYERS) {
            return 0; // TILE_NONE
        }
        
        const TileBehaviorLayer& layer = behavior_layers[layer_idx];
        if (x < 0 || x >= (int)layer.width || y < 0 || y >= (int)layer.height) {
            return 0; // TILE_NONE
        }
        
        return layer.data[y * layer.width + x];
    }


    // ============================================================================
    // PixelRoot32 Tile Animation System
    // Generated by PixelRoot32 Tilemap Editor
    // 
    // Data Format:
    // - TileAnimation: 4-byte POD structure stored in PROGMEM
    // - TileAnimationManager: Engine runtime system with O(1) frame resolution
    // - Global sync: All tiles with same base_tile animate together
    // ============================================================================

    // Animation definitions for layer: Ground
    static const pixelroot32::graphics::TileAnimation PIXELROOT32_SCENE_FLASH_ATTR GROUND_TILE_ANIMATIONS[] = {
        { 35, 8, 8, 0 },  // Watter11
        { 27, 8, 8, 0 }  // Watter12
    };

    static const uint8_t GROUND_TILE_ANIMATION_COUNT = 2;

    pixelroot32::graphics::TileAnimationManager& getGroundAnimManager();
    
    // Animation definitions for layer: Details
    static const pixelroot32::graphics::TileAnimation PIXELROOT32_SCENE_FLASH_ATTR DETAILS_TILE_ANIMATIONS[] = {
        { 5, 4, 8, 0 },  // Bonfire
        { 1, 4, 8, 0 },  // Watter13
        { 10, 4, 8, 0 }  // Torch
    };

    static const uint8_t DETAILS_TILE_ANIMATION_COUNT = 3;

    pixelroot32::graphics::TileAnimationManager& getDetailsAnimManager();

} // namespace animatedtiles

#endif // ANIMATEDTILES_H
