// Generated by the midway_clone asset exporter - DO NOT EDIT BY HAND.
//
// The exporter and its ASCII art source are not versioned; see this example's
// README for what they are and where they live. Edit the art there and
// re-export - hand edits here are lost on the next run.
//
// Engine: PixelRoot32
// Mode: 4bpp

#ifndef MIDWAY_EFFECTSPRITES_H
#define MIDWAY_EFFECTSPRITES_H

#include "platforms/PlatformDefaults.h"

#ifdef PIXELROOT32_ENABLE_4BPP_SPRITES

#include "graphics/Renderer.h"
#include "assets/SpritePalette.h"
#include <stdint.h>

/**
 * @file EffectSprites.h
 * @brief Tracers and explosions.
 *
 * Projectiles are 8x8: a bullet is read by its color and its motion, never by
 * its shape, so spending 16x16 on one would cost four times the blit for
 * nothing. Player fire is a yellow vertical stroke, enemy fire a red disc -
 * shape and color both differ, so the distinction survives for a colorblind
 * player.
 */

namespace midway_clone {

    static const uint8_t BULLET_WIDTH  = 8;
    static const uint8_t BULLET_HEIGHT = 8;

    /**
     * Player tracer. A vertical stroke - it reads as speed.
     */
    static const uint16_t BULLET_PLAYER_4BPP[] = {
        0x9100, 0x0019,
        0x9100, 0x0019,
        0x9100, 0x0019,
        0x9100, 0x0019,
        0x9100, 0x0019,
        0x9100, 0x0019,
        0x1000, 0x0001,
        0x0000, 0x0000,
    };

    /**
     * Enemy round. Compact and round - it reads as a threat.
     */
    static const uint16_t BULLET_ENEMY_4BPP[] = {
        0x1100, 0x0011,
        0x8810, 0x0188,
        0x8810, 0x0188,
        0x8810, 0x0188,
        0x8810, 0x0188,
        0x1100, 0x0011,
        0x0000, 0x0000,
        0x0000, 0x0000,
    };

    /**
     * @brief BULLET frames as engine sprite descriptors.
     *
     * Index with BULLETFrame below rather than by number.
     */
    static const pixelroot32::graphics::Sprite4bpp BULLET_FRAMES[] = {
        { reinterpret_cast<const uint8_t*>(BULLET_PLAYER_4BPP), SPRITE_PALETTE_MAPPING, BULLET_WIDTH, BULLET_HEIGHT, 16 },
        { reinterpret_cast<const uint8_t*>(BULLET_ENEMY_4BPP), SPRITE_PALETTE_MAPPING, BULLET_WIDTH, BULLET_HEIGHT, 16 },
    };

    enum BULLETFrame : uint8_t {
        BULLET_PLAYER = 0,
        BULLET_ENEMY = 1,
    };

    /**
     * @brief Frames in BULLET_FRAMES.
     *
     * Exported rather than left for callers to count, because the callers that
     * need it are animation loops deciding when a sequence has ended - and a
     * hand-written count is the kind that survives one frame being added.
     */
    static const uint8_t BULLET_FRAME_COUNT = 2;

    static const uint8_t EXPLOSION_WIDTH  = 16;
    static const uint8_t EXPLOSION_HEIGHT = 16;

    /**
     * Ignition. Small, and the only frame with a white core.
     */
    static const uint16_t EXPLOSION_A_4BPP[] = {
        0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x9990, 0x0999, 0x0000,
        0x0000, 0x2299, 0x9922, 0x0000,
        0x0000, 0x2299, 0x9922, 0x0000,
        0x0000, 0x9990, 0x0999, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000,
    };

    /**
     * Full bloom. Orange body, core still hot.
     */
    static const uint16_t EXPLOSION_B_4BPP[] = {
        0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0xAA00, 0x00AA, 0x0000,
        0x0000, 0x99AA, 0xAA99, 0x0000,
        0xA000, 0x299A, 0xA992, 0x000A,
        0xAA00, 0x2299, 0x9922, 0x00AA,
        0xAA00, 0x2299, 0x9922, 0x00AA,
        0xA000, 0x299A, 0xA992, 0x000A,
        0x0000, 0x99AA, 0xAA99, 0x0000,
        0x0000, 0xAA00, 0x00AA, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000,
    };

    /**
     * Dissipating. A broken ring - the center has already cleared.
     */
    static const uint16_t EXPLOSION_C_4BPP[] = {
        0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0xBBBB, 0xBBBB, 0x0000,
        0xBB00, 0xAA00, 0x00AA, 0x00BB,
        0x0BB0, 0x0AA0, 0x0AA0, 0x0BB0,
        0x00BB, 0x00AA, 0xAA00, 0xBB00,
        0xA00B, 0x0000, 0x0000, 0xB00A,
        0xA00B, 0x0000, 0x0000, 0xB00A,
        0x00BB, 0x00AA, 0xAA00, 0xBB00,
        0x0BB0, 0x0AA0, 0x0AA0, 0x0BB0,
        0xBB00, 0xAA00, 0x00AA, 0x00BB,
        0x0000, 0xBBBB, 0xBBBB, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000,
    };

    /**
     * @brief EXPLOSION frames as engine sprite descriptors.
     *
     * Index with EXPLOSIONFrame below rather than by number.
     */
    static const pixelroot32::graphics::Sprite4bpp EXPLOSION_FRAMES[] = {
        { reinterpret_cast<const uint8_t*>(EXPLOSION_A_4BPP), SPRITE_PALETTE_MAPPING, EXPLOSION_WIDTH, EXPLOSION_HEIGHT, 16 },
        { reinterpret_cast<const uint8_t*>(EXPLOSION_B_4BPP), SPRITE_PALETTE_MAPPING, EXPLOSION_WIDTH, EXPLOSION_HEIGHT, 16 },
        { reinterpret_cast<const uint8_t*>(EXPLOSION_C_4BPP), SPRITE_PALETTE_MAPPING, EXPLOSION_WIDTH, EXPLOSION_HEIGHT, 16 },
    };

    enum EXPLOSIONFrame : uint8_t {
        EXPLOSION_A = 0,
        EXPLOSION_B = 1,
        EXPLOSION_C = 2,
    };

    /**
     * @brief Frames in EXPLOSION_FRAMES.
     *
     * Exported rather than left for callers to count, because the callers that
     * need it are animation loops deciding when a sequence has ended - and a
     * hand-written count is the kind that survives one frame being added.
     */
    static const uint8_t EXPLOSION_FRAME_COUNT = 3;

} // namespace midway_clone

#endif // PIXELROOT32_ENABLE_4BPP_SPRITES

#endif // MIDWAY_EFFECTSPRITES_H
