// Generated by the midway_clone asset exporter - DO NOT EDIT BY HAND.
//
// The exporter and its ASCII art source are not versioned; see this example's
// README for what they are and where they live. Edit the art there and
// re-export - hand edits here are lost on the next run.
//
// Engine: PixelRoot32
// Mode: 4bpp

#ifndef MIDWAY_ENEMYSPRITES_H
#define MIDWAY_ENEMYSPRITES_H

#include "platforms/PlatformDefaults.h"

#ifdef PIXELROOT32_ENABLE_4BPP_SPRITES

#include "graphics/Renderer.h"
#include "assets/SpritePalette.h"
#include <stdint.h>

/**
 * @file EnemySprites.h
 * @brief Enemy aircraft, drawn nose-south - flying at the player, which is the
 *        only direction they ever travel.
 */

namespace midway_clone {

    static const uint8_t ENEMY_WIDTH  = 16;
    static const uint8_t ENEMY_HEIGHT = 16;

    /**
     * Diving at the player, propeller at one angle.
     */
    static const uint16_t ENEMY_FIGHTER_A_4BPP[] = {
        0x0000, 0x7100, 0x0017, 0x0000,
        0x0000, 0x6671, 0x1766, 0x0000,
        0x0000, 0x6671, 0x1766, 0x0000,
        0x0000, 0x6100, 0x0016, 0x0000,
        0x0000, 0x6100, 0x0016, 0x0000,
        0x0000, 0x5610, 0x0165, 0x0000,
        0x0000, 0x5610, 0x0165, 0x0000,
        0x6671, 0x6666, 0x6666, 0x1766,
        0x6671, 0x6668, 0x8666, 0x1766,
        0x6610, 0x6666, 0x6666, 0x0166,
        0x0000, 0x6100, 0x0016, 0x0000,
        0x0000, 0x6100, 0x0016, 0x0000,
        0x0000, 0x6610, 0x0166, 0x0000,
        0x0000, 0x9100, 0x0019, 0x0000,
        0x0000, 0x9991, 0x1999, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000,
    };

    /**
     * Diving at the player, propeller half a turn on.
     */
    static const uint16_t ENEMY_FIGHTER_B_4BPP[] = {
        0x0000, 0x7100, 0x0017, 0x0000,
        0x0000, 0x6671, 0x1766, 0x0000,
        0x0000, 0x6671, 0x1766, 0x0000,
        0x0000, 0x6100, 0x0016, 0x0000,
        0x0000, 0x6100, 0x0016, 0x0000,
        0x0000, 0x5610, 0x0165, 0x0000,
        0x0000, 0x5610, 0x0165, 0x0000,
        0x6671, 0x6666, 0x6666, 0x1766,
        0x6671, 0x6668, 0x8666, 0x1766,
        0x6610, 0x6666, 0x6666, 0x0166,
        0x0000, 0x6100, 0x0016, 0x0000,
        0x0000, 0x6100, 0x0016, 0x0000,
        0x0000, 0x6610, 0x0166, 0x0000,
        0x0000, 0x9100, 0x0019, 0x0000,
        0x0000, 0x9910, 0x0199, 0x0000,
        0x0000, 0x0000, 0x0000, 0x0000,
    };

    /**
     * @brief ENEMY frames as engine sprite descriptors.
     *
     * Index with ENEMYFrame below rather than by number.
     */
    static const pixelroot32::graphics::Sprite4bpp ENEMY_FRAMES[] = {
        { reinterpret_cast<const uint8_t*>(ENEMY_FIGHTER_A_4BPP), SPRITE_PALETTE_MAPPING, ENEMY_WIDTH, ENEMY_HEIGHT, 16 },
        { reinterpret_cast<const uint8_t*>(ENEMY_FIGHTER_B_4BPP), SPRITE_PALETTE_MAPPING, ENEMY_WIDTH, ENEMY_HEIGHT, 16 },
    };

    enum ENEMYFrame : uint8_t {
        ENEMY_FIGHTER_A = 0,
        ENEMY_FIGHTER_B = 1,
    };

    /**
     * @brief Frames in ENEMY_FRAMES.
     *
     * Exported rather than left for callers to count, because the callers that
     * need it are animation loops deciding when a sequence has ended - and a
     * hand-written count is the kind that survives one frame being added.
     */
    static const uint8_t ENEMY_FRAME_COUNT = 2;

} // namespace midway_clone

#endif // PIXELROOT32_ENABLE_4BPP_SPRITES

#endif // MIDWAY_ENEMYSPRITES_H
