// Generated by the midway_clone asset exporter - DO NOT EDIT BY HAND.
//
// The exporter and its ASCII art source are not versioned; see this example's
// README for what they are and where they live. Edit the art there and
// re-export - hand edits here are lost on the next run.
//
// Engine: PixelRoot32
// Mode: 4bpp

#ifndef MIDWAY_OCEAN_TILEMAP_H
#define MIDWAY_OCEAN_TILEMAP_H

#include "platforms/PlatformDefaults.h"

#ifdef PIXELROOT32_ENABLE_4BPP_SPRITES

#include "graphics/Renderer.h"
#include <stdint.h>

/**
 * @file OceanTileMap.h
 * @brief The stage: 15x100 tiles of ocean, islands and one carrier.
 *
 * Tiles are 16x16, the same size legend_of_clone and metroidvania use.
 * The NES original is an 8x8 machine and this map was 8x8 first, which drew a
 * better coastline; it was doubled for frame rate. The renderer pays a per-tile
 * cost that does not shrink with the tile, so a 240x240 screen costs 900 blits
 * at 8px and 225 at 16px for the identical 57,600 pixels.
 *
 * Row 0 is the NORTH end of the stage. The camera starts at the bottom and
 * climbs, so the player meets the highest row numbers first.
 */

namespace midway_clone {
namespace ocean {

    // --- Dimensions ---
    static const uint8_t  TILE_SIZE  = 16;
    static const uint8_t  MAP_WIDTH  = 15;
    static const uint8_t  MAP_HEIGHT = 100;
    static const uint16_t TILE_COUNT = 8;

    // --- Tile ids ---
    // 1-based: drawTileMap skips index 0, so slot 0 is reserved and never drawn.

    /**
     * Reserved slot 0. Never drawn.
     */
    static const uint8_t TILE_EMPTY = 0;

    /**
     * Open water. Flat blue with sparse deep-water flecks.
     *      *
     *      * The flecks are single pixels, not clusters. A cluster at this scale
     *      * reads as an object floating on the sea; a lone pixel reads as depth.
     */
    static const uint8_t TILE_OCEAN = 1;

    /**
     * Open water carrying a swell. Cyan crests in short horizontal dashes.
     *      *
     *      * Scattered through OCEAN at roughly one in six, this is what keeps a
     *      * scrolling sea from looking like a solid blue sheet sliding past.
     *      * The dashes are horizontal because the scroll is vertical: a crest
     *      * perpendicular to the motion is the one the eye can track.
     */
    static const uint8_t TILE_OCEAN_WAVE = 2;

    /**
     * Churning white water. Laid as a one-tile ring around every island.
     *      *
     *      * This is the whole shoreline treatment. Directional shore tiles - one
     *      * per edge and one per corner - would cost eight tiles instead of one
     *      * and buy an outline the player never looks at, because in a shmup the
     *      * eye is on the aircraft. The NES made this same trade.
     */
    static const uint8_t TILE_FOAM = 3;

    /**
     * Beach. Flat, with brown grit so a wide beach does not read as a hole in
     *      * the screen where the art should be.
     */
    static const uint8_t TILE_SAND = 4;

    /**
     * Island vegetation. Body green, sparsely shaded.
     */
    static const uint8_t TILE_GRASS = 5;

    /**
     * Island rock, laid in a running bond.
     *      *
     *      * The offset between courses is what makes a block of these read as one
     *      * rock mass. A grid-aligned bond reads as a grid of stamps - the exact
     *      * failure legend_of_clone's mountain tile was rebuilt to fix.
     */
    static const uint8_t TILE_ROCK = 6;

    /**
     * Carrier flight deck. Wooden planking, seams across the scroll axis.
     *      *
     *      * The seams run across the direction of travel, so a carrier sliding down
     *      * the screen shows its length passing rather than sitting still.
     *      *
     *      * Wood, not the gray steel a carrier suggests: the player's airframe is
     *      * bare aluminium at #BCBCBC, and a gray deck swallowed the aircraft whole
     *      * the moment it crossed one. Wartime flight decks really were planked, so
     *      * the color that reads is also the one that is correct.
     */
    static const uint8_t TILE_DECK = 7;

    /**
     * @brief Whether a tile is land, indexed by tile id.
     *
     * Nothing in this game collides with terrain - an aircraft overflies the
     * whole map, which is why there is no TILE_SOLID table here the way
     * legend_of_clone has one. This marks where ground targets can stand.
     */
    extern const bool TILE_IS_LAND[TILE_COUNT];

    /** The drawable layer. Valid only after init(). */
    extern pixelroot32::graphics::TileMap4bpp sea;

    /**
     * @brief Wires the descriptors above to the exported data.
     *
     * Idempotent, and cheap: it assigns pointers, it does not copy pixels.
     * Call once before drawing.
     */
    void init();

} // namespace ocean
} // namespace midway_clone

#endif // PIXELROOT32_ENABLE_4BPP_SPRITES

#endif // MIDWAY_OCEAN_TILEMAP_H
