// Generated by the midway_clone asset exporter - DO NOT EDIT BY HAND.
//
// The exporter and its ASCII art source are not versioned; see this example's
// README for what they are and where they live. Edit the art there and
// re-export - hand edits here are lost on the next run.
//
// Engine: PixelRoot32
// Mode: 4bpp

#ifndef MIDWAY_PLAYERSPRITES_H
#define MIDWAY_PLAYERSPRITES_H

#include "platforms/PlatformDefaults.h"

#ifdef PIXELROOT32_ENABLE_4BPP_SPRITES

#include "graphics/Renderer.h"
#include "assets/SpritePalette.h"
#include <stdint.h>

/**
 * @file PlayerSprites.h
 * @brief The player's P-38: level flight with a two-frame propeller, plus a
 *        banked frame each way.
 *
 * The twin-boom silhouette was picked over a single-engine fighter because at
 * 16x16 an aircraft has about a 12x14 usable footprint, and a shape with two
 * hard vertical lines through it stays legible against a moving sea. A single
 * fuselage at this size is a blob.
 *
 * Only the propeller hub pixels differ between the two level frames. A
 * propeller does not need to be drawn, it needs to flicker.
 */

namespace midway_clone {

    static const uint8_t PLAYER_WIDTH  = 16;
    static const uint8_t PLAYER_HEIGHT = 16;

    /**
     * Flying level, propeller blades caught at one angle.
     *      *
     *      * The wing shades along its trailing edge, not in patches. A top-down
     *      * wing catches light on the leading edge and loses it toward the back,
     *      * so one dark row at the bottom of the wing is the whole read - scattered
     *      * shadow pixels just look like damage.
     *      *
     *      * The tailplane spans between the booms and no further. Drawing it as wide
     *      * as the main wing is the single fastest way to make a P-38 stop looking
     *      * like one.
     */
    static const uint16_t PLAYER_LEVEL_A_4BPP[] = {
        0x3100, 0x1001, 0x1001, 0x0013,
        0x9100, 0x3101, 0x1013, 0x0019,
        0x3100, 0x3101, 0x1013, 0x0013,
        0x3100, 0x5101, 0x1015, 0x0013,
        0x3100, 0x5101, 0x1015, 0x0013,
        0x3100, 0x3101, 0x1013, 0x0013,
        0x3310, 0x3333, 0x3333, 0x0133,
        0x3331, 0x3333, 0x3333, 0x1333,
        0x4431, 0x3333, 0x3333, 0x1344,
        0x4410, 0x4444, 0x4444, 0x0144,
        0x3100, 0x3101, 0x1013, 0x0013,
        0x3100, 0x1001, 0x1001, 0x0013,
        0x3100, 0x0001, 0x1000, 0x0013,
        0x3100, 0x0001, 0x1000, 0x0013,
        0x3100, 0x3333, 0x3333, 0x0013,
        0x1100, 0x1111, 0x1111, 0x0011,
    };

    /**
     * Flying level, propeller half a turn on.
     *      *
     *      * Only the two hub pixels change between A and B. That is the entire
     *      * animation and it is enough - a propeller does not need to be drawn,
     *      * it needs to flicker. Animating the airframe as well would make the
     *      * aircraft look like it is flexing in flight.
     */
    static const uint16_t PLAYER_LEVEL_B_4BPP[] = {
        0x9100, 0x1001, 0x1001, 0x0019,
        0x3100, 0x3101, 0x1013, 0x0013,
        0x3100, 0x3101, 0x1013, 0x0013,
        0x3100, 0x5101, 0x1015, 0x0013,
        0x3100, 0x5101, 0x1015, 0x0013,
        0x3100, 0x3101, 0x1013, 0x0013,
        0x3310, 0x3333, 0x3333, 0x0133,
        0x3331, 0x3333, 0x3333, 0x1333,
        0x4431, 0x3333, 0x3333, 0x1344,
        0x4410, 0x4444, 0x4444, 0x0144,
        0x3100, 0x3101, 0x1013, 0x0013,
        0x3100, 0x1001, 0x1001, 0x0013,
        0x3100, 0x0001, 0x1000, 0x0013,
        0x3100, 0x0001, 0x1000, 0x0013,
        0x3100, 0x3333, 0x3333, 0x0013,
        0x1100, 0x1111, 0x1111, 0x0011,
    };

    /**
     * Rolled left.
     *      *
     *      * The whole airframe shifts one pixel left AND the right wing loses two,
     *      * because roll is foreshortening, not translation. A frame that only
     *      * shifts reads as the aircraft teleporting sideways.
     */
    static const uint16_t PLAYER_BANK_LEFT_4BPP[] = {
        0x1310, 0x1100, 0x3100, 0x0001,
        0x1910, 0x3310, 0x9101, 0x0001,
        0x1310, 0x3310, 0x3101, 0x0001,
        0x1310, 0x5510, 0x3101, 0x0001,
        0x1310, 0x5510, 0x3101, 0x0001,
        0x1310, 0x3310, 0x3101, 0x0001,
        0x3331, 0x3333, 0x3333, 0x0001,
        0x3331, 0x3333, 0x3333, 0x0013,
        0x4431, 0x3333, 0x4433, 0x0013,
        0x4410, 0x4444, 0x4444, 0x0001,
        0x1310, 0x3310, 0x3101, 0x0001,
        0x1310, 0x1100, 0x3100, 0x0001,
        0x1310, 0x0000, 0x3100, 0x0001,
        0x1310, 0x0000, 0x3100, 0x0001,
        0x3310, 0x3333, 0x3333, 0x0001,
        0x1110, 0x1111, 0x1111, 0x0001,
    };

    /**
     * Rolled right. Mirror of the left bank.
     */
    static const uint16_t PLAYER_BANK_RIGHT_4BPP[] = {
        0x1000, 0x0013, 0x0011, 0x0131,
        0x1000, 0x1019, 0x0133, 0x0191,
        0x1000, 0x1013, 0x0133, 0x0131,
        0x1000, 0x1013, 0x0155, 0x0131,
        0x1000, 0x1013, 0x0155, 0x0131,
        0x1000, 0x1013, 0x0133, 0x0131,
        0x1000, 0x3333, 0x3333, 0x1333,
        0x3100, 0x3333, 0x3333, 0x1333,
        0x3100, 0x3344, 0x3333, 0x1344,
        0x1000, 0x4444, 0x4444, 0x0144,
        0x1000, 0x1013, 0x0133, 0x0131,
        0x1000, 0x0013, 0x0011, 0x0131,
        0x1000, 0x0013, 0x0000, 0x0131,
        0x1000, 0x0013, 0x0000, 0x0131,
        0x1000, 0x3333, 0x3333, 0x0133,
        0x1000, 0x1111, 0x1111, 0x0111,
    };

    /**
     * @brief PLAYER frames as engine sprite descriptors.
     *
     * Index with PLAYERFrame below rather than by number.
     */
    static const pixelroot32::graphics::Sprite4bpp PLAYER_FRAMES[] = {
        { reinterpret_cast<const uint8_t*>(PLAYER_LEVEL_A_4BPP), SPRITE_PALETTE_MAPPING, PLAYER_WIDTH, PLAYER_HEIGHT, 16 },
        { reinterpret_cast<const uint8_t*>(PLAYER_LEVEL_B_4BPP), SPRITE_PALETTE_MAPPING, PLAYER_WIDTH, PLAYER_HEIGHT, 16 },
        { reinterpret_cast<const uint8_t*>(PLAYER_BANK_LEFT_4BPP), SPRITE_PALETTE_MAPPING, PLAYER_WIDTH, PLAYER_HEIGHT, 16 },
        { reinterpret_cast<const uint8_t*>(PLAYER_BANK_RIGHT_4BPP), SPRITE_PALETTE_MAPPING, PLAYER_WIDTH, PLAYER_HEIGHT, 16 },
    };

    enum PLAYERFrame : uint8_t {
        PLAYER_LEVEL_A = 0,
        PLAYER_LEVEL_B = 1,
        PLAYER_BANK_LEFT = 2,
        PLAYER_BANK_RIGHT = 3,
    };

    /**
     * @brief Frames in PLAYER_FRAMES.
     *
     * Exported rather than left for callers to count, because the callers that
     * need it are animation loops deciding when a sequence has ended - and a
     * hand-written count is the kind that survives one frame being added.
     */
    static const uint8_t PLAYER_FRAME_COUNT = 4;

} // namespace midway_clone

#endif // PIXELROOT32_ENABLE_4BPP_SPRITES

#endif // MIDWAY_PLAYERSPRITES_H
