// Generated by the midway_clone asset exporter - DO NOT EDIT BY HAND.
//
// The exporter and its ASCII art source are not versioned; see this example's
// README for what they are and where they live. Edit the art there and
// re-export - hand edits here are lost on the next run.
//
// Engine: PixelRoot32
// Mode: 4bpp

#ifndef MIDWAY_SPRITEPALETTE_H
#define MIDWAY_SPRITEPALETTE_H

#include "graphics/Renderer.h"
#include <stdint.h>

/**
 * @file SpritePalette.h
 * @brief The 16 RGB565 colors every aircraft, tracer and explosion draws with.
 *
 * Installed with setSpriteCustomPalette(). Separate from the tilemap palette
 * because dual palette mode gives sprites their own 16 slots - so the sea and
 * the aircraft are not competing for the same table.
 *
 * Player and enemy share no color except black. On a screen holding a dozen
 * aircraft that is what keeps the two apart at a glance.
 */

namespace midway_clone {

    // --- RGB565 by engine Color slot ---
    // Indexed by Color, NOT by 4bpp pixel value. Slots the art never uses keep
    // their conventional color so Color::Red still renders red for text.
    static const uint16_t SPRITE_PALETTE_DATA[16] = {
        0x0000, //  0 Black  'k'  #000000  outline on every aircraft
        0xFFFF, //  1 White  'w'  #FCFCFC  specular highlight, explosion core
        0x0015, //  2 Navy - unused by art, conventional value kept
        0x3DFF, //  3 Blue  'c'  #3CBCFC  canopy glass
        0x7BEF, //  4 Cyan  's'  #7C7C7C  player airframe, shaded. NOT cyan: this slot holds a mid gray because the sprite table has no second gray and the player needs two
        0x03C0, //  5 DarkGreen  'd'  #007800  enemy airframe, shaded
        0x0540, //  6 Green  'g'  #00A800  enemy airframe - IJN green
        0xBFC3, //  7 LightGreen - unused by art, conventional value kept
        0xFF34, //  8 Yellow  'f'  #FCE4A0  propeller blur, muzzle flash, player tracer
        0xFBC0, //  9 Orange  'o'  #F87800  explosion body
        0xF9C0, // 10 LightRed  'h'  #F83800  hinomaru roundels, enemy tracer
        0xF800, // 11 Red - unused by art, conventional value kept
        0xA880, // 12 DarkRed  'e'  #A81000  explosion, dissipating
        0x6A3F, // 13 Purple - unused by art, conventional value kept
        0xFBDF, // 14 Magenta - unused by art, conventional value kept
        0xBDF7, // 15 Gray  'y'  #BCBCBC  player airframe - bare aluminium
    };

    // --- 4bpp pixel value to engine Color slot ---
    // The blitter reads sprite.palette[pixelValue] as a Color and resolves that
    // slot against the table above. Entry 0 is never read: pixel value 0 is a
    // hole, so the first real color has to live at value 1.
    static const pixelroot32::graphics::Color SPRITE_PALETTE_MAPPING[16] = {
        pixelroot32::graphics::Color::Black, //  0 transparent - never read
        pixelroot32::graphics::Color::Black, //  1 'k' -> Black
        pixelroot32::graphics::Color::White, //  2 'w' -> White
        pixelroot32::graphics::Color::Gray, //  3 'y' -> Gray
        pixelroot32::graphics::Color::Cyan, //  4 's' -> Cyan
        pixelroot32::graphics::Color::Blue, //  5 'c' -> Blue
        pixelroot32::graphics::Color::Green, //  6 'g' -> Green
        pixelroot32::graphics::Color::DarkGreen, //  7 'd' -> DarkGreen
        pixelroot32::graphics::Color::LightRed, //  8 'h' -> LightRed
        pixelroot32::graphics::Color::Yellow, //  9 'f' -> Yellow
        pixelroot32::graphics::Color::Orange, // 10 'o' -> Orange
        pixelroot32::graphics::Color::DarkRed, // 11 'e' -> DarkRed
        pixelroot32::graphics::Color::Black, // 12 unused
        pixelroot32::graphics::Color::Black, // 13 unused
        pixelroot32::graphics::Color::Black, // 14 unused
        pixelroot32::graphics::Color::Black, // 15 unused
    };

} // namespace midway_clone

#endif // MIDWAY_SPRITEPALETTE_H
