// Generated by the midway_clone asset exporter - DO NOT EDIT BY HAND.
//
// The exporter and its ASCII art source are not versioned; see this example's
// README for what they are and where they live. Edit the art there and
// re-export - hand edits here are lost on the next run.
//
// Engine: PixelRoot32
// Mode: 4bpp

#ifndef MIDWAY_TILEMAPPALETTE_H
#define MIDWAY_TILEMAPPALETTE_H

#include "graphics/Renderer.h"
#include <stdint.h>

/**
 * @file TilemapPalette.h
 * @brief The 16 RGB565 colors the sea and the islands render with.
 *
 * Installed with setBackgroundCustomPalette(). The engine stores the pointer
 * without copying, which is why this lives at namespace scope.
 *
 * Sampled against the NES palette: three blues for water depth, one cyan for
 * foam, and the same sand and rock browns any 8-bit island is built from.
 */

namespace midway_clone {

    // --- RGB565 by engine Color slot ---
    // Indexed by Color, NOT by 4bpp pixel value. Slots the art never uses keep
    // their conventional color so Color::Red still renders red for text.
    static const uint16_t TILEMAP_PALETTE_DATA[16] = {
        0x0000, //  0 Black  'k'  #000000  outlines, deck planking, rock mortar
        0xFFFF, //  1 White - unused by art, conventional value kept
        0x0015, //  2 Navy  'n'  #0000A8  deep ocean - the darker water between swells
        0x02DF, //  3 Blue  'b'  #0058F8  open ocean - the sea's body color
        0x3DFF, //  4 Cyan  'c'  #3CBCFC  foam and wave crests
        0x03C0, //  5 DarkGreen  'd'  #007800  island foliage, shaded
        0x0540, //  6 Green  'g'  #00A800  island foliage, lit
        0xBFC3, //  7 LightGreen - unused by art, conventional value kept
        0xEE94, //  8 Yellow  'a'  #E8D0A0  beach sand
        0xAAA0, //  9 Orange  'o'  #A85400  island rock, lit face
        0xFBCB, // 10 LightRed - unused by art, conventional value kept
        0xF800, // 11 Red - unused by art, conventional value kept
        0x71C0, // 12 DarkRed  'r'  #703800  island rock shaded face, and carrier decking
        0x6A3F, // 13 Purple - unused by art, conventional value kept
        0xFBDF, // 14 Magenta - unused by art, conventional value kept
        0xBDF7, // 15 Gray - unused by art, conventional value kept
    };

    // --- 4bpp pixel value to engine Color slot ---
    // The blitter reads sprite.palette[pixelValue] as a Color and resolves that
    // slot against the table above. Entry 0 is never read: pixel value 0 is a
    // hole, so the first real color has to live at value 1.
    static const pixelroot32::graphics::Color TILEMAP_PALETTE_MAPPING[16] = {
        pixelroot32::graphics::Color::Black, //  0 transparent - never read
        pixelroot32::graphics::Color::Black, //  1 'k' -> Black
        pixelroot32::graphics::Color::Navy, //  2 'n' -> Navy
        pixelroot32::graphics::Color::Blue, //  3 'b' -> Blue
        pixelroot32::graphics::Color::Cyan, //  4 'c' -> Cyan
        pixelroot32::graphics::Color::DarkGreen, //  5 'd' -> DarkGreen
        pixelroot32::graphics::Color::Green, //  6 'g' -> Green
        pixelroot32::graphics::Color::Yellow, //  7 'a' -> Yellow
        pixelroot32::graphics::Color::Orange, //  8 'o' -> Orange
        pixelroot32::graphics::Color::DarkRed, //  9 'r' -> DarkRed
        pixelroot32::graphics::Color::Black, // 10 unused
        pixelroot32::graphics::Color::Black, // 11 unused
        pixelroot32::graphics::Color::Black, // 12 unused
        pixelroot32::graphics::Color::Black, // 13 unused
        pixelroot32::graphics::Color::Black, // 14 unused
        pixelroot32::graphics::Color::Black, // 15 unused
    };

} // namespace midway_clone

#endif // MIDWAY_TILEMAPPALETTE_H
