// GENERATED - do not edit by hand.
#ifndef ISODUNGEONROOMTILEMAP_MAIN_SCENE_H
#define ISODUNGEONROOMTILEMAP_MAIN_SCENE_H

#include "platforms/PlatformDefaults.h"

#include "math/Projection.h"
#include <stdint.h>

/**
 * PixelRoot32 Exported Scene: IsoDungeonRoomTileMap
 * Generated by PixelRoot32 Tilemap Editor
 *
 * @file IsoDungeonRoomTileMap.h
 * @brief The dungeon's three room maps, their shared tileset, and the
 *        projection that places them -- an ISOMETRIC export.
 *
 * ### What this file is for
 *
 * It is the reference output an isometric map must export, written by hand
 * ahead of the generator that will emit it. Read it beside the orthogonal
 * reference export, examples/metroidvania/src/assets/MetroidvaniaSceneOneTileMap.h:
 * everything the two share is deliberate, and everything they do not share is
 * a field the orthogonal generator has no way to emit today.
 *
 * ### The three things an isometric export adds
 *
 * **1. A rectangular tile, and a stride that is not the sprite height.**
 * The orthogonal export emits one `TILE_SIZE` and assigns it to both
 * `tileWidth` and `tileHeight`. That cannot express this map. `TILE_HEIGHT`
 * here is 16 -- the vertical distance between neighbouring cell centres --
 * while a WALL bitmap is 40 px tall. Tiles are taller than their cells and
 * overhang them, which is what an extruded block IS.
 *
 * **2. A per-tile foot row (`TILESET_FOOT_Y`).**
 * An orthogonal tile fills its cell, so its position is its cell's corner and
 * nothing more is needed. An isometric tile is anchored: `TILESET_FOOT_Y[id]`
 * is the bitmap row that must land on the target cell's diamond CENTRE, and
 * the renderer places the sprite at `centreY - footY`. Without it every tile
 * would need the same extrusion height, which defeats the point.
 *
 * **3. A projection (`ISO_PROJECTION`).**
 * Six integers saying where cell (0, 0) lands and how far one step along each
 * cell axis moves on screen. An orthogonal map does not need one because its
 * projection is the identity. Everything isometric about this file is those
 * six numbers -- there is no isometric mode and no diamond-specific renderer.
 *
 * ### Why the projection block sits OUTSIDE the 4bpp guard
 *
 * Not a slip. The tileset and the maps are 4bpp data and are correctly gated
 * on PIXELROOT32_ENABLE_4BPP_SPRITES, but the projection is pure geometry:
 * gameplay code needs it to place the hero and the props at cells where it
 * draws no tile at all. Gating it would make a game that turns 4bpp off fail
 * to compile for reasons that have nothing to do with sprites. An isometric
 * export must emit its geometry unguarded.
 *
 * ### Rooms, not simultaneous layers
 *
 * The orthogonal reference exports three layers -- background, platforms,
 * stairs -- drawn together over one another. The three maps here are
 * ALTERNATIVES: exactly one room is on screen at a time. The emitted shape is
 * identical either way (N index arrays plus N TileMap4bpp sharing one
 * tileset), which is why one template covers both, but a consumer must not
 * assume it should draw them all.
 *
 * ### `inline constexpr`, where the orthogonal export writes `static const`
 *
 * A deviation with a reason, not a style preference. The orthogonal reference
 * export declares its dimensions `static const`, which gives every including
 * translation unit its own internal-linkage copy. That is harmless there,
 * because only the export's own .cpp reads them. Here they cross TU
 * boundaries: gameplay code names `MAP_WIDTH` to size its room, and an
 * internal-linkage constant cannot legally initialise the `inline constexpr`
 * it is assigned to. An isometric export must emit `inline constexpr`.
 *
 * ### Consuming it
 *
 * @code
 * // IsoDungeonScene::init()
 * iso_dungeon::init();
 * gfx::setDualCustomPalette(TILEMAP_PALETTE_DATA, TILEMAP_PALETTE_DATA);
 *
 * // RoomRenderer::drawTiles()
 * renderer.drawTileMap(*ROOM_LAYERS[roomIndex], 0, 0,
 *                      gfx::LayerType::Static, ISO_PROJECTION);
 * @endcode
 *
 * Note the palette call: setDualCustomPalette, not setBackgroundCustomPalette.
 * See IsoDungeonRoomTileMapPalette.h for why loading only the background bank
 * silently mis-colours every sprite that shares this mapping.
 */

namespace iso_dungeon {

    // --- Tile Dimensions ---
    // TILE_WIDTH/TILE_HEIGHT are the CELL STRIDE, not the tileset's bitmap
    // extents. A tile may be -- and here usually is -- taller than its cell.
    inline constexpr uint8_t TILE_WIDTH  = 32;
    inline constexpr uint8_t TILE_HEIGHT = 16;
    inline constexpr uint8_t MAP_WIDTH   = 7;
    inline constexpr uint8_t MAP_HEIGHT  = 7;

    // --- Projection ---
    /**
     * Where cell (0, 0)'s diamond CENTRE lands, and what one step along each
     * cell axis does on screen: +1 cellX steps right and down, +1 cellY steps
     * left and down. The classic 2:1 isometric basis.
     *
     * The origin is the diamond centre rather than a sprite corner because
     * every anchor in TILESET_FOOT_Y is measured to that same point.
     */
    inline constexpr pixelroot32::math::ProjectionSpec ISO_PROJECTION{
        120, 88,
         16,  8,
        -16,  8};

    // Enforcement is caller-side by contract: a plain aggregate cannot assert
    // its own initializers under -fno-exceptions, so an export states its
    // invariants here, at the declaration site.
    static_assert(pixelroot32::math::projectionSpecIsValid(ISO_PROJECTION, MAP_WIDTH, MAP_HEIGHT),
                  "ISO_PROJECTION exceeds Scalar's fixed-point range for this map size.");
    static_assert(pixelroot32::math::projectionDet(ISO_PROJECTION) == 256,
                  "ISO_PROJECTION's determinant is no longer a power of two; "
                  "screenToCell would stop strength-reducing to a shift.");
    static_assert(pixelroot32::math::rowMajorIsPainterOrder(ISO_PROJECTION),
                  "ISO_PROJECTION no longer makes row-major iteration a back-to-front "
                  "paint order. The projected drawTileMap path has no depth sort and "
                  "relies on it; see math::rowMajorIsPainterOrder in include/math/Projection.h.");

} // namespace iso_dungeon

#ifdef PIXELROOT32_ENABLE_4BPP_SPRITES

#include "graphics/Renderer.h"

namespace iso_dungeon {

    // --- Tileset ---
    /// Sentinel at index 0 plus six real tiles. See the .cpp for why the
    /// isometric empty slot has ZERO extent rather than being an all-zero
    /// tile of full size, the way the orthogonal export emits it.
    inline constexpr uint16_t TILESET_TILE_COUNT = 7;

    extern const pixelroot32::graphics::Sprite4bpp TILESET_SPRITES[TILESET_TILE_COUNT];

    /// Bitmap row of each tile that lands on its cell's diamond centre.
    /// Parallel to TILESET_SPRITES, per TileMapGeneric::tileFootY's contract.
    /// The orthogonal export has no analogue of this table.
    extern const uint8_t TILESET_FOOT_Y[TILESET_TILE_COUNT];

    // --- Layer Definitions ---

    extern pixelroot32::graphics::TileMap4bpp room0;

    extern pixelroot32::graphics::TileMap4bpp room1;

    extern pixelroot32::graphics::TileMap4bpp room2;

    inline constexpr uint8_t NUM_ROOM_LAYERS = 3;

    /// Indexed by room number, so a consumer selects a room without a switch.
    extern pixelroot32::graphics::TileMap4bpp* const ROOM_LAYERS[NUM_ROOM_LAYERS];

    /**
     * Initializes the scene components.
     * Call this once before drawing in the render loop.
     */
    void init();

} // namespace iso_dungeon

#endif // PIXELROOT32_ENABLE_4BPP_SPRITES

#endif // ISODUNGEONROOMTILEMAP_MAIN_SCENE_H
