; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = native
extra_configs = lib/platformio.ini

[env:native]
extends = base_native
lib_deps = gperez88/PixelRoot32-Game-Engine@^1.1.0
build_flags = 
    ${base_native.build_flags}
    -D PHYSICAL_DISPLAY_WIDTH=128
    -D PHYSICAL_DISPLAY_HEIGHT=128
    -Isrc
    -Iinclude
    -I.pio/libdeps/native/PixelRoot32-Game-Engine/include
    -I.pio/libdeps/native/PixelRoot32-Game-Engine/src
    -IC:/msys64/mingw64/include/SDL2
    -LC:/msys64/mingw64/lib
    -O2
    -Wall
    -Wextra
    -lSDL2
    -mconsole

[env:esp32dev]
extends = base_esp32
board = esp32dev
framework = arduino
lib_deps = gperez88/PixelRoot32-Game-Engine@^1.1.0
build_flags = 
    ${base_esp32.build_flags}
    -D PHYSICAL_DISPLAY_WIDTH=128
    -D PHYSICAL_DISPLAY_HEIGHT=128
    -D PLATFORM_ESP32DEV
    ; TFT config (ST7735 128x128)
    -D USER_SETUP_LOADED=1
    -D ST7735_DRIVER
    -D ST7735_GREENTAB3
    -D TFT_WIDTH=128
    -D TFT_HEIGHT=128
    -D TFT_MOSI=23
    -D TFT_SCLK=18
    -D TFT_DC=2
    -D TFT_RST=4
    -D TFT_CS=-1
    -D SPI_FREQUENCY=27000000
    -D SPI_READ_FREQUENCY=20000000
    -Isrc
    -O2
