#pragma once
#include <cstdint>
#include "graphics/Color.h"

namespace pixelroot32::graphics::particles {
/**
 * @struct ParticleConfig
 * @brief Configuration parameters for a particle emitter.
 *
 * Defines the behavior and appearance of particles generated by an emitter.
 * Allows defining ranges for randomness (speed, life).
 */
struct ParticleConfig {
    Color startColor; ///< Color at the beginning of the particle's life.   
    Color endColor;   ///< Color at the end of the particle's life.

    float minSpeed; ///< Minimum initial speed.
    float maxSpeed; ///< Maximum initial speed.

    float gravity;  ///< Gravity force applied to Y velocity each frame.
    float friction; ///< Air resistance factor (0.0 - 1.0) applied to velocity.

    uint8_t minLife; ///< Minimum lifetime in frames/ticks.
    uint8_t maxLife; ///< Maximum lifetime in frames/ticks.

    bool fadeColor; ///< If true, interpolates color from startColor to endColor.
    float minAngleDeg; ///< Minimum emission angle in degrees (0 = right).
    float maxAngleDeg; ///< Maximum emission angle in degrees.
};

}
