// Generated by PixelRoot32 Sprite Compiler
// Engine: PixelRoot32
// Mode: 4bpp
// Source: NES - Bomberman - Miscellaneous - General Sprites.png
//         (Hudson Soft, local-only reference. Not redistributable.)

#pragma once
#include "graphics/Color.h"
#include <stdint.h>

namespace bomberman {

using pixelroot32::graphics::Color;

static constexpr uint8_t kBombermanPaletteSize = 16;

static const Color BOMBERMAN_PALETTE_MAPPING[16] = {
    (Color)0,  (Color)1,  (Color)2,  (Color)3,
    (Color)4,  (Color)5,  (Color)6,  (Color)7,
    (Color)8,  (Color)9,  (Color)10, (Color)11,
    (Color)12, (Color)13, (Color)14, (Color)15,
};

static const Color PLAYER_PALETTE_MAPPING[16] = {
    (Color)0, (Color)3, (Color)5, (Color)13,
    (Color)15, (Color)0, (Color)0, (Color)0,
    (Color)0, (Color)0, (Color)0, (Color)0,
    (Color)0, (Color)0, (Color)0, (Color)0,
};

static const uint16_t BOMBERMAN_SPRITE_PALETTE_RGB565[16] = {
    // Palette (RGB565)
    // Index 0: Transparent -> mapped to game-floor green so the background
    //                          board and the green slice background of actor
    //                          sprites (enemies, items, bombs) read as one
    //                          continuous floor instead of a coloured halo.
    0x3C20,  // 0: Green (acts as background)

    // Index 1: Black. Originally 0x0000, but packRgb565ToTftSprite8(0x0000)
    //          returns 0, which the 8bpp framebuffer treats as transparent,
    //          so the dark outline of hard walls, enemies, and items was
    //          disappearing. 0x0841 is the darkest "near-black" that still
    //          packs to a non-zero 8bpp value, so the outline draws as black
    //          on screen while still reading as the same hue.
    0x0841,  // 1: Black (near-black, packed != 0)
    0x0A40,  // 2: Dark Green       - RGB(12, 72, 0)
    0x3C20,  // 3: Green            - RGB(56, 135, 0)
    0x50E0,  // 4: Brown            - RGB(86, 29, 0)
    0x659F,  // 5: Light Blue       - RGB(100, 176, 255)
    0x6B60,  // 6: Olive            - RGB(107, 109, 0)
    0x9A60,  // 7: Orange Brown     - RGB(153, 78, 0)
    0xB596,  // 8: Light Gray       - RGB(176, 176, 176)
    0xB984,  // 9: Brick Red        - RGB(181, 49, 32)
    0xB8EF,  // 10: Magenta         - RGB(183, 30, 123)
    0xBDE0,  // 11: Yellow Green    - RGB(188, 190, 0)
    0xF6D4,  // 12: Peach           - RGB(247, 216, 165)
    0xFC0E,  // 13: Coral           - RGB(255, 129, 112)
    0xFE58,  // 14: Light Pink      - RGB(255, 204, 197)
    0xFFFF,  // 15: White           - RGB(255, 255, 255)
};
} // namespace bomberman
