#ifndef METROIDVANIASCENEONETILEMAP_MAIN_SCENE_H
#define METROIDVANIASCENEONETILEMAP_MAIN_SCENE_H

#include "platforms/PlatformDefaults.h"

#ifdef PIXELROOT32_ENABLE_4BPP_SPRITES

#include "graphics/Renderer.h"
#include <stdint.h>

/**
 * PixelRoot32 Exported Scene: MetroidvaniaSceneOneTileMap
 * Generated by PixelRoot32 Tilemap Editor
 */

namespace metroidvania {

    // --- Tile Dimensions ---
    static const uint8_t TILE_SIZE = 8;
    static const uint8_t MAP_WIDTH = 40;
    static const uint8_t MAP_HEIGHT = 30;

    // --- Layer Definitions ---
    
    extern pixelroot32::graphics::TileMap4bpp background;
    
    extern pixelroot32::graphics::TileMap4bpp platforms;
    
    extern pixelroot32::graphics::TileMap4bpp stairs;
    

    /**
     * Initializes the scene components. 
     * Call this once before drawing in the render loop.
     */
    void init();

} // namespace metroidvania

#endif // PIXELROOT32_ENABLE_4BPP_SPRITES

#endif // METROIDVANIASCENEONETILEMAP_H