#ifndef METROIDVANIASCENEONETILEMAP_TILEMAP_PALETTE_H
#define METROIDVANIASCENEONETILEMAP_TILEMAP_PALETTE_H

#include "graphics/Renderer.h"
#include <stdint.h>

/**
 * PixelRoot32 Shared Tilemap Palette
 * Generated by PixelRoot32 Tilemap Editor
 */

namespace metroidvania {

    // --- Shared Palette Definitions ---
    
    // RGB565 Palette Data (16 colors)
    // Used for tilemap layers (background, platforms, stairs).
    // Must be passed to setBackgroundCustomPalette() for correct rendering.
    static const uint16_t TILEMAP_PALETTE_DATA[] = {
        0x0000, // 0: Transparent/Black
        0x1885, // 1: RGB(31, 16, 42) - Dark blue/purple (background)
        0x3B2C, // 2: RGB(62, 101, 97) - Dark green (platform surface)
        0x5D2E, // 3: RGB(91, 166, 117) - Moss green (platform)
        0x60CA, // 4: RGB(97, 24, 81) - Dark red (platform edge)
        0x6E4D, // 5: RGB(107, 201, 108) - Vibrant green (platform edge)
        0x81AA, // 6: RGB(135, 53, 85) - Reddish (stair support)
        0xA2AB, // 7: RGB(166, 85, 95) - Salmon/red (stair steps)
        0xCB8E, // 8: RGB(201, 115, 115) - Peach/salmon (accents)
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000 // 9-15: fill
    };

    // Color indices mapping for Sprites
    static const pixelroot32::graphics::Color TILEMAP_PALETTE_MAPPING[] = {
        (pixelroot32::graphics::Color)0, // Transparent
        (pixelroot32::graphics::Color)1, // blue
        (pixelroot32::graphics::Color)2, // green
        (pixelroot32::graphics::Color)3, // green
        (pixelroot32::graphics::Color)4, // red
        (pixelroot32::graphics::Color)5, // green
        (pixelroot32::graphics::Color)6, // red
        (pixelroot32::graphics::Color)7, // red
        (pixelroot32::graphics::Color)8 // peach/salmon
        };

} // namespace metroidvania

#endif // METROIDVANIASCENEONETILEMAP_TILEMAP_PALETTE_H