// Generated by PixelRoot32 Tool Suite. Do not edit.
#pragma once

#include <audio/AudioMusicTypes.h>
#include <audio/AudioTypes.h>
#include <cstddef>

namespace musicdemo::moonwell_hymn {

static constexpr float S = 0.25f;
static constexpr float E = 0.5f;
static constexpr float Q = 1.0f;
static constexpr float H = 2.0f;
static constexpr float W = 4.0f;

static const float kBpm = 104.0f;

inline constexpr pixelroot32::audio::InstrumentPreset kInstrument_LIB_DRUM_CRASH{0.25999999f, 0.0f, 7, 0.219999999f, 10, 0.000500000024f, 0.280000001f, 0.0f, 0.0799999982f, pixelroot32::audio::LfoTarget::NONE, 0.0f, 0.0f, 0.0f, true, 0.0f, 0.0f, 0.0f};
inline constexpr pixelroot32::audio::InstrumentPreset kInstrument_LIB_DRUM_OPEN_HAT{0.219999999f, 0.0f, 4, 0.119999997f, 11, 0.000500000024f, 0.150000006f, 0.0f, 0.0199999996f, pixelroot32::audio::LfoTarget::NONE, 0.0f, 0.0f, 0.0f, true, 0.0f, 0.0f, 0.0f};
inline constexpr pixelroot32::audio::InstrumentPreset kInstrument_LIB_DRUM_RIDE{0.219999999f, 0.0f, 7, 0.159999996f, 9, 0.000500000024f, 0.180000007f, 0.0f, 0.0500000007f, pixelroot32::audio::LfoTarget::NONE, 0.0f, 0.0f, 0.0f, true, 0.0f, 0.0f, 0.0f};
inline constexpr pixelroot32::audio::InstrumentPreset kInstrument_LIB_DRUM_SOFT_SNARE{0.280000001f, 0.0f, 2, 0.119999997f, 20, 0.00100000005f, 0.100000001f, 0.0f, 0.0599999987f, pixelroot32::audio::LfoTarget::NONE, 0.0f, 0.0f, 0.0f, true, 0.0f, 0.0f, 0.0f};
inline constexpr pixelroot32::audio::InstrumentPreset kInstrument_LIB_SINE_AIR_PAD{0.239999995f, 0.5f, 4, 0.0f, 0, 0.119999997f, 0.449999988f, 0.800000012f, 0.699999988f, pixelroot32::audio::LfoTarget::VOLUME, 1.20000005f, 0.109999999f, 0.400000006f, false, 0.0f, 0.0f, 0.0f};
inline constexpr pixelroot32::audio::InstrumentPreset kInstrument_LIB_SINE_BELL{0.319999993f, 0.5f, 5, 0.0f, 0, 0.00200000009f, 0.319999993f, 0.219999999f, 0.219999999f, pixelroot32::audio::LfoTarget::NONE, 0.0f, 0.0f, 0.0f, false, 0.0f, 0.0f, 0.0f};
inline constexpr pixelroot32::audio::InstrumentPreset kInstrument_LIB_SINE_DREAM_PAD{0.219999999f, 0.5f, 5, 0.0f, 0, 0.150000006f, 0.479999989f, 0.779999971f, 0.75f, pixelroot32::audio::LfoTarget::VOLUME, 1.0f, 0.119999997f, 0.449999988f, false, 0.0f, 0.0f, 0.0f};
inline constexpr pixelroot32::audio::InstrumentPreset kInstrument_LIB_SINE_FLUTE{0.300000012f, 0.5f, 5, 0.0f, 0, 0.0149999997f, 0.119999997f, 0.879999995f, 0.200000003f, pixelroot32::audio::LfoTarget::PITCH, 5.0f, 0.0179999992f, 0.200000003f, false, 0.0f, 0.0f, 0.0f};
inline constexpr pixelroot32::audio::InstrumentPreset kInstrument_LIB_SINE_GLASS{0.280000001f, 0.5f, 6, 0.0f, 0, 0.00200000009f, 0.280000001f, 0.349999994f, 0.280000001f, pixelroot32::audio::LfoTarget::NONE, 0.0f, 0.0f, 0.0f, false, 0.0f, 0.0f, 0.0f};
inline constexpr pixelroot32::audio::InstrumentPreset kInstrument_LIB_TRIANGLE_SUB_BASS{0.400000006f, 0.5f, 1, 0.0f, 0, 0.00400000019f, 0.119999997f, 0.649999976f, 0.159999996f, pixelroot32::audio::LfoTarget::NONE, 0.0f, 0.0f, 0.0f, false, 0.0f, 0.0f, 0.0f};

static const pixelroot32::audio::MusicNote kLeadNotes[] = {
    {pixelroot32::audio::Note::A, 4, Q, 0.130199999f, &kInstrument_LIB_SINE_FLUTE},
    {pixelroot32::audio::Note::C, 5, Q, 0.133920014f, &kInstrument_LIB_SINE_FLUTE},
    {pixelroot32::audio::Note::E, 5, Q, 0.139500007f, &kInstrument_LIB_SINE_FLUTE},
    {pixelroot32::audio::Note::D, 5, 0.75f, 0.130199999f, &kInstrument_LIB_SINE_FLUTE},
    {pixelroot32::audio::Note::E, 5, S, 0.0892799944f, &kInstrument_LIB_SINE_BELL},
    {pixelroot32::audio::Note::C, 5, Q, 0.133920014f, &kInstrument_LIB_SINE_FLUTE},
    {pixelroot32::audio::Note::B, 4, Q, 0.126479998f, &kInstrument_LIB_SINE_FLUTE},
    {pixelroot32::audio::Note::A, 4, Q, 0.130199999f, &kInstrument_LIB_SINE_FLUTE},
    {pixelroot32::audio::Note::E, 4, Q, 0.120899998f, &kInstrument_LIB_SINE_FLUTE},
    {pixelroot32::audio::Note::F, 4, Q, 0.126479998f, &kInstrument_LIB_SINE_FLUTE},
    {pixelroot32::audio::Note::A, 4, Q, 0.133920014f, &kInstrument_LIB_SINE_FLUTE},
    {pixelroot32::audio::Note::C, 5, Q, 0.139500007f, &kInstrument_LIB_SINE_FLUTE},
    {pixelroot32::audio::Note::B, 4, 0.75f, 0.130199999f, &kInstrument_LIB_SINE_FLUTE},
    {pixelroot32::audio::Note::C, 5, S, 0.0892799944f, &kInstrument_LIB_SINE_BELL},
    {pixelroot32::audio::Note::A, 4, Q, 0.133920014f, &kInstrument_LIB_SINE_FLUTE},
    {pixelroot32::audio::Note::G, 4, E, 0.126479998f, &kInstrument_LIB_SINE_FLUTE},
    {pixelroot32::audio::Note::A, 4, E, 0.130199999f, &kInstrument_LIB_SINE_FLUTE},
    {pixelroot32::audio::Note::E, 5, Q, 0.135407999f, &kInstrument_LIB_SINE_GLASS},
    {pixelroot32::audio::Note::A, 4, Q, 0.133920014f, &kInstrument_LIB_SINE_FLUTE},
    {pixelroot32::audio::Note::A, 4, Q, 0.130199999f, &kInstrument_LIB_SINE_FLUTE},
    {pixelroot32::audio::Note::C, 5, Q, 0.133920014f, &kInstrument_LIB_SINE_FLUTE},
    {pixelroot32::audio::Note::E, 5, Q, 0.139500007f, &kInstrument_LIB_SINE_FLUTE},
    {pixelroot32::audio::Note::D, 5, 0.75f, 0.130199999f, &kInstrument_LIB_SINE_FLUTE},
    {pixelroot32::audio::Note::E, 5, S, 0.0892799944f, &kInstrument_LIB_SINE_BELL},
    {pixelroot32::audio::Note::C, 5, Q, 0.133920014f, &kInstrument_LIB_SINE_FLUTE},
    {pixelroot32::audio::Note::B, 4, Q, 0.126479998f, &kInstrument_LIB_SINE_FLUTE},
    {pixelroot32::audio::Note::A, 4, Q, 0.130199999f, &kInstrument_LIB_SINE_FLUTE},
    {pixelroot32::audio::Note::E, 4, Q, 0.120899998f, &kInstrument_LIB_SINE_FLUTE},
    {pixelroot32::audio::Note::F, 4, Q, 0.126479998f, &kInstrument_LIB_SINE_FLUTE},
    {pixelroot32::audio::Note::A, 4, Q, 0.133920014f, &kInstrument_LIB_SINE_FLUTE},
    {pixelroot32::audio::Note::C, 5, Q, 0.139500007f, &kInstrument_LIB_SINE_FLUTE},
    {pixelroot32::audio::Note::B, 4, 0.75f, 0.130199999f, &kInstrument_LIB_SINE_FLUTE},
    {pixelroot32::audio::Note::C, 5, S, 0.0892799944f, &kInstrument_LIB_SINE_BELL},
    {pixelroot32::audio::Note::A, 4, Q, 0.133920014f, &kInstrument_LIB_SINE_FLUTE},
    {pixelroot32::audio::Note::G, 4, E, 0.126479998f, &kInstrument_LIB_SINE_FLUTE},
    {pixelroot32::audio::Note::A, 4, E, 0.130199999f, &kInstrument_LIB_SINE_FLUTE},
    {pixelroot32::audio::Note::E, 5, Q, 0.135407999f, &kInstrument_LIB_SINE_GLASS},
    {pixelroot32::audio::Note::A, 4, Q, 0.133920014f, &kInstrument_LIB_SINE_FLUTE},
};
static const pixelroot32::audio::MusicNote kBassNotes[] = {
    {pixelroot32::audio::Note::A, 2, 1.5f, 0.210000008f, &kInstrument_LIB_TRIANGLE_SUB_BASS},
    {pixelroot32::audio::Note::A, 3, E, 0.153999999f, &kInstrument_LIB_TRIANGLE_SUB_BASS},
    {pixelroot32::audio::Note::A, 2, 1.5f, 0.210000008f, &kInstrument_LIB_TRIANGLE_SUB_BASS},
    {pixelroot32::audio::Note::A, 3, E, 0.153999999f, &kInstrument_LIB_TRIANGLE_SUB_BASS},
    {pixelroot32::audio::Note::F, 2, 1.5f, 0.210000008f, &kInstrument_LIB_TRIANGLE_SUB_BASS},
    {pixelroot32::audio::Note::F, 3, E, 0.153999999f, &kInstrument_LIB_TRIANGLE_SUB_BASS},
    {pixelroot32::audio::Note::E, 2, 1.5f, 0.210000008f, &kInstrument_LIB_TRIANGLE_SUB_BASS},
    {pixelroot32::audio::Note::E, 3, E, 0.153999999f, &kInstrument_LIB_TRIANGLE_SUB_BASS},
    {pixelroot32::audio::Note::D, 2, 1.5f, 0.210000008f, &kInstrument_LIB_TRIANGLE_SUB_BASS},
    {pixelroot32::audio::Note::D, 3, E, 0.153999999f, &kInstrument_LIB_TRIANGLE_SUB_BASS},
    {pixelroot32::audio::Note::E, 2, 1.5f, 0.210000008f, &kInstrument_LIB_TRIANGLE_SUB_BASS},
    {pixelroot32::audio::Note::E, 3, E, 0.153999999f, &kInstrument_LIB_TRIANGLE_SUB_BASS},
    {pixelroot32::audio::Note::F, 2, 1.5f, 0.210000008f, &kInstrument_LIB_TRIANGLE_SUB_BASS},
    {pixelroot32::audio::Note::F, 3, E, 0.153999999f, &kInstrument_LIB_TRIANGLE_SUB_BASS},
    {pixelroot32::audio::Note::A, 2, 1.5f, 0.210000008f, &kInstrument_LIB_TRIANGLE_SUB_BASS},
    {pixelroot32::audio::Note::A, 3, E, 0.153999999f, &kInstrument_LIB_TRIANGLE_SUB_BASS},
    {pixelroot32::audio::Note::A, 2, 1.5f, 0.210000008f, &kInstrument_LIB_TRIANGLE_SUB_BASS},
    {pixelroot32::audio::Note::A, 3, E, 0.153999999f, &kInstrument_LIB_TRIANGLE_SUB_BASS},
    {pixelroot32::audio::Note::A, 2, 1.5f, 0.210000008f, &kInstrument_LIB_TRIANGLE_SUB_BASS},
    {pixelroot32::audio::Note::A, 3, E, 0.153999999f, &kInstrument_LIB_TRIANGLE_SUB_BASS},
    {pixelroot32::audio::Note::F, 2, 1.5f, 0.210000008f, &kInstrument_LIB_TRIANGLE_SUB_BASS},
    {pixelroot32::audio::Note::F, 3, E, 0.153999999f, &kInstrument_LIB_TRIANGLE_SUB_BASS},
    {pixelroot32::audio::Note::E, 2, 1.5f, 0.210000008f, &kInstrument_LIB_TRIANGLE_SUB_BASS},
    {pixelroot32::audio::Note::E, 3, E, 0.153999999f, &kInstrument_LIB_TRIANGLE_SUB_BASS},
    {pixelroot32::audio::Note::D, 2, 1.5f, 0.210000008f, &kInstrument_LIB_TRIANGLE_SUB_BASS},
    {pixelroot32::audio::Note::D, 3, E, 0.153999999f, &kInstrument_LIB_TRIANGLE_SUB_BASS},
    {pixelroot32::audio::Note::E, 2, 1.5f, 0.210000008f, &kInstrument_LIB_TRIANGLE_SUB_BASS},
    {pixelroot32::audio::Note::E, 3, E, 0.153999999f, &kInstrument_LIB_TRIANGLE_SUB_BASS},
    {pixelroot32::audio::Note::F, 2, 1.5f, 0.210000008f, &kInstrument_LIB_TRIANGLE_SUB_BASS},
    {pixelroot32::audio::Note::F, 3, E, 0.153999999f, &kInstrument_LIB_TRIANGLE_SUB_BASS},
    {pixelroot32::audio::Note::A, 2, 1.5f, 0.210000008f, &kInstrument_LIB_TRIANGLE_SUB_BASS},
    {pixelroot32::audio::Note::A, 3, E, 0.153999999f, &kInstrument_LIB_TRIANGLE_SUB_BASS},
};
static const pixelroot32::audio::MusicNote kHarmonyNotes[] = {
    {pixelroot32::audio::Note::A, 3, H, 0.0334400013f, &kInstrument_LIB_SINE_DREAM_PAD},
    {pixelroot32::audio::Note::E, 4, H, 0.0317679979f, &kInstrument_LIB_SINE_DREAM_PAD},
    {pixelroot32::audio::Note::F, 3, H, 0.0334400013f, &kInstrument_LIB_SINE_DREAM_PAD},
    {pixelroot32::audio::Note::E, 3, H, 0.0317679979f, &kInstrument_LIB_SINE_DREAM_PAD},
    {pixelroot32::audio::Note::D, 3, H, 0.0364799984f, &kInstrument_LIB_SINE_AIR_PAD},
    {pixelroot32::audio::Note::E, 3, H, 0.0346559957f, &kInstrument_LIB_SINE_AIR_PAD},
    {pixelroot32::audio::Note::F, 3, H, 0.0334400013f, &kInstrument_LIB_SINE_DREAM_PAD},
    {pixelroot32::audio::Note::A, 3, H, 0.0351119973f, &kInstrument_LIB_SINE_DREAM_PAD},
    {pixelroot32::audio::Note::A, 3, H, 0.0334400013f, &kInstrument_LIB_SINE_DREAM_PAD},
    {pixelroot32::audio::Note::E, 4, H, 0.0317679979f, &kInstrument_LIB_SINE_DREAM_PAD},
    {pixelroot32::audio::Note::F, 3, H, 0.0334400013f, &kInstrument_LIB_SINE_DREAM_PAD},
    {pixelroot32::audio::Note::E, 3, H, 0.0317679979f, &kInstrument_LIB_SINE_DREAM_PAD},
    {pixelroot32::audio::Note::D, 3, H, 0.0364799984f, &kInstrument_LIB_SINE_AIR_PAD},
    {pixelroot32::audio::Note::E, 3, H, 0.0346559957f, &kInstrument_LIB_SINE_AIR_PAD},
    {pixelroot32::audio::Note::F, 3, H, 0.0334400013f, &kInstrument_LIB_SINE_DREAM_PAD},
    {pixelroot32::audio::Note::A, 3, H, 0.0351119973f, &kInstrument_LIB_SINE_DREAM_PAD},
};
static const pixelroot32::audio::MusicNote kDrumsNotes[] = {
    {pixelroot32::audio::Note::Rest, 1, 0.0f, 0.0989999995f, &pixelroot32::audio::INSTR_KICK},
    {pixelroot32::audio::Note::Rest, 1, E, 0.0416000001f, &kInstrument_LIB_DRUM_CRASH},
    {pixelroot32::audio::Note::Rest, 1, E, 0.0246399995f, &kInstrument_LIB_DRUM_RIDE},
    {pixelroot32::audio::Note::Rest, 1, E, 0.0448000021f, &kInstrument_LIB_DRUM_SOFT_SNARE},
    {pixelroot32::audio::Note::Rest, 1, E, 0.0246399995f, &kInstrument_LIB_DRUM_RIDE},
    {pixelroot32::audio::Note::Rest, 1, E, 0.0809999928f, &pixelroot32::audio::INSTR_KICK},
    {pixelroot32::audio::Note::Rest, 1, E, 0.0246399995f, &kInstrument_LIB_DRUM_RIDE},
    {pixelroot32::audio::Note::Rest, 1, E, 0.04256f, &kInstrument_LIB_DRUM_SOFT_SNARE},
    {pixelroot32::audio::Note::Rest, 1, 0.0f, 0.0264000017f, &kInstrument_LIB_DRUM_OPEN_HAT},
    {pixelroot32::audio::Note::Rest, 1, E, 0.0246399995f, &kInstrument_LIB_DRUM_RIDE},
    {pixelroot32::audio::Note::Rest, 1, E, 0.0989999995f, &pixelroot32::audio::INSTR_KICK},
    {pixelroot32::audio::Note::Rest, 1, E, 0.0246399995f, &kInstrument_LIB_DRUM_RIDE},
    {pixelroot32::audio::Note::Rest, 1, E, 0.0448000021f, &kInstrument_LIB_DRUM_SOFT_SNARE},
    {pixelroot32::audio::Note::Rest, 1, E, 0.0246399995f, &kInstrument_LIB_DRUM_RIDE},
    {pixelroot32::audio::Note::Rest, 1, E, 0.0809999928f, &pixelroot32::audio::INSTR_KICK},
    {pixelroot32::audio::Note::Rest, 1, E, 0.0246399995f, &kInstrument_LIB_DRUM_RIDE},
    {pixelroot32::audio::Note::Rest, 1, E, 0.04256f, &kInstrument_LIB_DRUM_SOFT_SNARE},
    {pixelroot32::audio::Note::Rest, 1, 0.0f, 0.0264000017f, &kInstrument_LIB_DRUM_OPEN_HAT},
    {pixelroot32::audio::Note::Rest, 1, E, 0.0246399995f, &kInstrument_LIB_DRUM_RIDE},
    {pixelroot32::audio::Note::Rest, 1, E, 0.0989999995f, &pixelroot32::audio::INSTR_KICK},
    {pixelroot32::audio::Note::Rest, 1, E, 0.0246399995f, &kInstrument_LIB_DRUM_RIDE},
    {pixelroot32::audio::Note::Rest, 1, E, 0.0448000021f, &kInstrument_LIB_DRUM_SOFT_SNARE},
    {pixelroot32::audio::Note::Rest, 1, E, 0.0246399995f, &kInstrument_LIB_DRUM_RIDE},
    {pixelroot32::audio::Note::Rest, 1, E, 0.0809999928f, &pixelroot32::audio::INSTR_KICK},
    {pixelroot32::audio::Note::Rest, 1, E, 0.0246399995f, &kInstrument_LIB_DRUM_RIDE},
    {pixelroot32::audio::Note::Rest, 1, E, 0.04256f, &kInstrument_LIB_DRUM_SOFT_SNARE},
    {pixelroot32::audio::Note::Rest, 1, 0.0f, 0.0264000017f, &kInstrument_LIB_DRUM_OPEN_HAT},
    {pixelroot32::audio::Note::Rest, 1, E, 0.0246399995f, &kInstrument_LIB_DRUM_RIDE},
    {pixelroot32::audio::Note::Rest, 1, E, 0.0989999995f, &pixelroot32::audio::INSTR_KICK},
    {pixelroot32::audio::Note::Rest, 1, E, 0.0246399995f, &kInstrument_LIB_DRUM_RIDE},
    {pixelroot32::audio::Note::Rest, 1, E, 0.0448000021f, &kInstrument_LIB_DRUM_SOFT_SNARE},
    {pixelroot32::audio::Note::Rest, 1, E, 0.0246399995f, &kInstrument_LIB_DRUM_RIDE},
    {pixelroot32::audio::Note::Rest, 1, E, 0.0809999928f, &pixelroot32::audio::INSTR_KICK},
    {pixelroot32::audio::Note::Rest, 1, E, 0.0246399995f, &kInstrument_LIB_DRUM_RIDE},
    {pixelroot32::audio::Note::Rest, 1, E, 0.04256f, &kInstrument_LIB_DRUM_SOFT_SNARE},
    {pixelroot32::audio::Note::Rest, 1, 0.0f, 0.0264000017f, &kInstrument_LIB_DRUM_OPEN_HAT},
    {pixelroot32::audio::Note::Rest, 1, E, 0.0246399995f, &kInstrument_LIB_DRUM_RIDE},
    {pixelroot32::audio::Note::Rest, 1, 0.0f, 0.0989999995f, &pixelroot32::audio::INSTR_KICK},
    {pixelroot32::audio::Note::Rest, 1, E, 0.0416000001f, &kInstrument_LIB_DRUM_CRASH},
    {pixelroot32::audio::Note::Rest, 1, E, 0.0246399995f, &kInstrument_LIB_DRUM_RIDE},
    {pixelroot32::audio::Note::Rest, 1, E, 0.0448000021f, &kInstrument_LIB_DRUM_SOFT_SNARE},
    {pixelroot32::audio::Note::Rest, 1, E, 0.0246399995f, &kInstrument_LIB_DRUM_RIDE},
    {pixelroot32::audio::Note::Rest, 1, E, 0.0809999928f, &pixelroot32::audio::INSTR_KICK},
    {pixelroot32::audio::Note::Rest, 1, E, 0.0246399995f, &kInstrument_LIB_DRUM_RIDE},
    {pixelroot32::audio::Note::Rest, 1, E, 0.04256f, &kInstrument_LIB_DRUM_SOFT_SNARE},
    {pixelroot32::audio::Note::Rest, 1, 0.0f, 0.0264000017f, &kInstrument_LIB_DRUM_OPEN_HAT},
    {pixelroot32::audio::Note::Rest, 1, E, 0.0246399995f, &kInstrument_LIB_DRUM_RIDE},
    {pixelroot32::audio::Note::Rest, 1, E, 0.0989999995f, &pixelroot32::audio::INSTR_KICK},
    {pixelroot32::audio::Note::Rest, 1, E, 0.0246399995f, &kInstrument_LIB_DRUM_RIDE},
    {pixelroot32::audio::Note::Rest, 1, E, 0.0448000021f, &kInstrument_LIB_DRUM_SOFT_SNARE},
    {pixelroot32::audio::Note::Rest, 1, E, 0.0246399995f, &kInstrument_LIB_DRUM_RIDE},
    {pixelroot32::audio::Note::Rest, 1, E, 0.0809999928f, &pixelroot32::audio::INSTR_KICK},
    {pixelroot32::audio::Note::Rest, 1, E, 0.0246399995f, &kInstrument_LIB_DRUM_RIDE},
    {pixelroot32::audio::Note::Rest, 1, E, 0.04256f, &kInstrument_LIB_DRUM_SOFT_SNARE},
    {pixelroot32::audio::Note::Rest, 1, 0.0f, 0.0264000017f, &kInstrument_LIB_DRUM_OPEN_HAT},
    {pixelroot32::audio::Note::Rest, 1, E, 0.0246399995f, &kInstrument_LIB_DRUM_RIDE},
    {pixelroot32::audio::Note::Rest, 1, E, 0.0989999995f, &pixelroot32::audio::INSTR_KICK},
    {pixelroot32::audio::Note::Rest, 1, E, 0.0246399995f, &kInstrument_LIB_DRUM_RIDE},
    {pixelroot32::audio::Note::Rest, 1, E, 0.0448000021f, &kInstrument_LIB_DRUM_SOFT_SNARE},
    {pixelroot32::audio::Note::Rest, 1, E, 0.0246399995f, &kInstrument_LIB_DRUM_RIDE},
    {pixelroot32::audio::Note::Rest, 1, E, 0.0809999928f, &pixelroot32::audio::INSTR_KICK},
    {pixelroot32::audio::Note::Rest, 1, E, 0.0246399995f, &kInstrument_LIB_DRUM_RIDE},
    {pixelroot32::audio::Note::Rest, 1, E, 0.04256f, &kInstrument_LIB_DRUM_SOFT_SNARE},
    {pixelroot32::audio::Note::Rest, 1, 0.0f, 0.0264000017f, &kInstrument_LIB_DRUM_OPEN_HAT},
    {pixelroot32::audio::Note::Rest, 1, E, 0.0246399995f, &kInstrument_LIB_DRUM_RIDE},
    {pixelroot32::audio::Note::Rest, 1, E, 0.0989999995f, &pixelroot32::audio::INSTR_KICK},
    {pixelroot32::audio::Note::Rest, 1, E, 0.0246399995f, &kInstrument_LIB_DRUM_RIDE},
    {pixelroot32::audio::Note::Rest, 1, E, 0.0448000021f, &kInstrument_LIB_DRUM_SOFT_SNARE},
    {pixelroot32::audio::Note::Rest, 1, E, 0.0246399995f, &kInstrument_LIB_DRUM_RIDE},
    {pixelroot32::audio::Note::Rest, 1, E, 0.0809999928f, &pixelroot32::audio::INSTR_KICK},
    {pixelroot32::audio::Note::Rest, 1, E, 0.0246399995f, &kInstrument_LIB_DRUM_RIDE},
    {pixelroot32::audio::Note::Rest, 1, E, 0.04256f, &kInstrument_LIB_DRUM_SOFT_SNARE},
    {pixelroot32::audio::Note::Rest, 1, 0.0f, 0.0264000017f, &kInstrument_LIB_DRUM_OPEN_HAT},
    {pixelroot32::audio::Note::Rest, 1, E, 0.0246399995f, &kInstrument_LIB_DRUM_RIDE},
};

static const pixelroot32::audio::MusicTrack kBassTrack = {
    kBassNotes,
    sizeof(kBassNotes) / sizeof(pixelroot32::audio::MusicNote),
    true,
    pixelroot32::audio::WaveType::TRIANGLE,
    0.5f, nullptr, nullptr, nullptr};

static const pixelroot32::audio::MusicTrack kHarmonyTrack = {
    kHarmonyNotes,
    sizeof(kHarmonyNotes) / sizeof(pixelroot32::audio::MusicNote),
    true,
    pixelroot32::audio::WaveType::SINE,
    0.5f, nullptr, nullptr, nullptr};

static const pixelroot32::audio::MusicTrack kDrumsTrack = {
    kDrumsNotes,
    sizeof(kDrumsNotes) / sizeof(pixelroot32::audio::MusicNote),
    true,
    pixelroot32::audio::WaveType::NOISE,
    0.5f, nullptr, nullptr, nullptr};

static const pixelroot32::audio::MusicTrack kTrack = {
    kLeadNotes,
    sizeof(kLeadNotes) / sizeof(pixelroot32::audio::MusicNote),
    true,
    pixelroot32::audio::WaveType::SINE,
    0.5f,
    &kBassTrack,
    &kHarmonyTrack,
    &kDrumsTrack,
};

}  // musicdemo::moonwell_hymn 
