#pragma once
#include <cstdint>

/**
 * @struct ParticleConfig
 * @brief Configuration parameters for a particle emitter.
 *
 * Defines the behavior and appearance of particles generated by an emitter.
 * Allows defining ranges for randomness (speed, life).
 */
struct ParticleConfig {
    uint16_t startColor; ///< Color at the beginning of the particle's life.
    uint16_t endColor;   ///< Color at the end of the particle's life.

    float minSpeed; ///< Minimum initial speed.
    float maxSpeed; ///< Maximum initial speed.

    float gravity;  ///< Gravity force applied to Y velocity each frame.
    float friction; ///< Air resistance factor (0.0 - 1.0) applied to velocity.

    uint8_t minLife; ///< Minimum lifetime in frames/ticks.
    uint8_t maxLife; ///< Maximum lifetime in frames/ticks.

    bool fadeColor; ///< If true, interpolates color from startColor to endColor.
};
