"""Generate original CC0 pixel-art headers for the Bomberbot example.

This script produces ORIGINAL sprite data (robot player, slime enemy,
bomb, fire cross explosion, and tiles) designed from scratch. It does NOT
extract or copy any copyrighted game artwork. Only the shared 16-color
palette and the engine's 4bpp packing format are reused.

Packing (matches Sprite4bpp in include/graphics/Renderer.h):
  - 16x16 @ 4bpp -> 8 bytes/row -> 4 uint16_t/row -> 64 uint16_t total.
  - Byte low nibble = left pixel, high nibble = right pixel.
  - uint16 = p0 | p1<<4 | p2<<8 | p3<<12 (little-endian byte order).
  - Palette index 0 in DATA means transparent (never drawn).
"""

import os

ASSETS = os.path.join("examples", "bomberbot", "src", "assets")

# Palette indexes (0 = transparent in sprite data)
G = 0   # transparent
K = 1   # black outline
DG = 2  # dark green
GR = 3  # green
BR = 4  # brown
LB = 5  # light blue
OL = 6  # olive
OB = 7  # orange brown
LG = 8  # light gray
RD = 9  # brick red
MG = 10 # magenta
YG = 11 # yellow green
PC = 12 # peach
CR = 13 # coral
PK = 14 # light pink
WH = 15 # white

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def pack(rows):
    """rows: list of 16 strings, each 16 chars of palette indexes (hex digit or '.'=0).
    Returns list of 64 uint16 values."""
    assert len(rows) == 16, f"need 16 rows, got {len(rows)}"
    out = []
    for row in rows:
        assert len(row) == 16, f"row width != 16: {row!r}"
        pixels = [G if c == '.' else int(c, 16) for c in row]
        for i in range(0, 16, 4):
            p0, p1, p2, p3 = pixels[i], pixels[i + 1], pixels[i + 2], pixels[i + 3]
            out.append(p0 | (p1 << 4) | (p2 << 8) | (p3 << 12))
    assert len(out) == 64
    return out


def fmt_array(name, values, comment=None):
    lines = []
    if comment:
        lines.append(f"// {comment}")
    lines.append(f"static const uint16_t {name}[64] = {{")
    for r in range(16):
        chunk = values[r * 4:(r + 1) * 4]
        lines.append("    " + ", ".join(f"0x{v:04X}" for v in chunk) + ("," if r < 15 else ""))
    lines.append("};")
    return lines


def fmt_sprite4(name, array_name, palette_map, comment=None):
    lines = []
    if comment:
        lines.append(f"// {comment}")
    lines.append(f"static const Sprite4bpp {name} = {{")
    lines.append(f"    reinterpret_cast<const uint8_t*>({array_name}),")
    lines.append(f"    {palette_map}, 16, 16, kBomberbotPaletteSize")
    lines.append("};")
    return lines


def fmt_sprite4_arr(name, entries, comment=None):
    lines = []
    if comment:
        lines.append(f"// {comment}")
    lines.append(f"static const Sprite4bpp {name}[{len(entries)}] = {{")
    for e in entries:
        lines.append(f"    {{ reinterpret_cast<const uint8_t*>({e}),")
        lines.append(f"      {PALETTE_MAP}, 16, 16, kBomberbotPaletteSize }},")
    lines.append("};")
    return lines


PALETTE_MAP = "BOMBERBOT_PALETTE_MAPPING"
PLAYER_MAP = "PLAYER_PALETTE_MAPPING"

HEADER_HEAD = """// Generated by PixelRoot32 Sprite Compiler
// Engine: PixelRoot32
// Mode: 4bpp
// Source: ORIGINAL CC0 pixel art (see examples/bomberbot/tools/generate_cc0_assets.py).
//         Designed from scratch for the PixelRoot32 demo. Not derived from any
//         copyrighted game artwork; free to use and redistribute.


#pragma once
#include "graphics/Renderer.h"
#include "BomberbotPalette.h"
#include <stdint.h>

namespace bomberbot {

using pixelroot32::graphics::Sprite4bpp;
"""

HEADER_TAIL = """
} // namespace bomberbot
"""

# ---------------------------------------------------------------------------
# Art: Bomb (3 pulse frames) - round black bomb with fuse spark
# ---------------------------------------------------------------------------

def bomb_frame(spark_col):
    # fuse spark position shifts per frame; white highlight top-left
    rows = [
        "................",
        ".......F1F......",
        "......F11F......",
        ".....F111F......",
        "....F11111F.....",
        "...F1111111F....",
        "...F1111111F....",
        "..F11111111F....",
        "..F1{0}1111111F...".format(spark_col),
        "..F111111111F...",
        "...F1111111F....",
        "...F11111111F...",
        "....F11111F.....",
        ".....F111F......",
        "......FFF.......",
        "................",
    ]
    # 8 = width of spark column check; patch row 8 spark position
    return rows


# Rebuild bomb with explicit per-frame spark rows (simpler than format above)
def bomb_rows(spark):
    r = ['.'] * 16
    r = [
        "................",
        ".......F1F......",
        "......F11F......",
        ".....F111F......",
        "....F11111F.....",
        "...F1111111F....",
        "...F1111111F....",
        "..F11111111F....",
        "..F1111{0}1111F...".format(spark),
        "..F111111111F...",
        "...F1111111F....",
        "...F11111111F...",
        "....F11111F.....",
        ".....F111F......",
        "......FFF.......",
        "................",
    ]
    return r


BOMB = {
    "BOMB_FRAME_0_4BPP": bomb_rows("D"),
    "BOMB_FRAME_1_4BPP": bomb_rows("F"),
    "BOMB_FRAME_2_4BPP": bomb_rows("1"),
}

# ---------------------------------------------------------------------------
# Art: Board tiles
# ---------------------------------------------------------------------------

HARD_WALL = [
    "8888888888888888",
    "8FFFFFFF8FFFFFF8",
    "8111111181111118",
    "8888888888888888",
    "8888888888888888",
    "8FFFFFFF8FFFFFF8",
    "8111111181111118",
    "8888888888888888",
    "8888888888888888",
    "8888888888888888",
    "8FFFFFFF8FFFFFF8",
    "8111111181111118",
    "8888888888888888",
    "8888888888888888",
    "8888888888888888",
    "8888888888888888",
]

SOFT_WALL = [
    "1111111111111111",
    "1BBBBBBBBBBBBBB1",
    "1B1111B1B1B111B1",
    "1B1FFB1B1BFF1B11",
    "1B1FFB1B1BFF1B11",
    "1B1111B1B1B111B1",
    "1BBBBBBBBBBBBBB1",
    "1B111111111111B1",
    "1B1B11111111B1B1",
    "1B1B1B1111B1B1B1",
    "1B1B1B1111B1B1B1",
    "1B1B11111111B1B1",
    "1B111111111111B1",
    "1BBBBBBBBBBBBBB1",
    "1111111111111111",
    "................",
]

EXIT = [
    "................",
    ".11111111111111.",
    ".14444444444441.",
    ".14447447774441.",
    ".14447447774441.",
    ".14444444444441.",
    ".14777777777741.",
    ".14444444444441.",
    ".14777777777741.",
    ".14444444444441.",
    ".14777777777741.",
    ".14444444444441.",
    ".1477F777777F41.",
    ".14444444444441.",
    ".11111111111111.",
    "................",
]

POWERUP_FIRE = [
    "................",
    "................",
    "......BBB.......",
    ".....BBBBBB.....",
    "....BBBBBBBB....",
    "....BDBBBBBB....",
    "...BBDDBBBBBB...",
    "...BBDDDBBBBB...",
    "...BBFFDBBBB....",
    "..BBFFFFFFB.....",
    "..BBFFFFFFBB....",
    "..BFFFFFFFFB....",
    "...BFFFFFFB.....",
    "....BBBBBB......",
    "................",
    "................",
]

POWERUP_BOMB = [
    "................",
    ".......FF.......",
    "......FBBF......",
    ".....FBBBBF.....",
    "....FBBBBB1F....",
    "...FBBBBBBB1F...",
    "...FBBBBBBB1F...",
    "..FBBBBBBBB1F...",
    "..FBBBBBBBB1F...",
    "..FBBBBBBBB1F...",
    "...FBBBBBBB1F...",
    "...FBBBBBBB1F...",
    "....FBBBBB1F....",
    ".....FBBBBF.....",
    "......FFFF......",
    "................",
]

# 14 power-up icons (index 0 = fire, 8 = bomb are used by the game; the rest
# are original placeholder icons kept for the future).
POWERUP_ALL = {
    0: POWERUP_FIRE,
    8: POWERUP_BOMB,
    1: [  # heart
        "................",
        "..DD.....DD.....",
        ".DDDD.D.DDDD....",
        "DDDDDDDDDDDDD...",
        ".DDDDDDDDDDD....",
        "..DDDDDDDDD.....",
        "...DDDDDDD......",
        "....DDDDD.......",
        ".....DDD........",
        "......D.........",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
    ],
    2: [  # star
        "................",
        "......FF........",
        ".....FFFF.......",
        ".....FFFF.......",
        "FFFFFFFFFFF.....",
        ".FFFFFFFFF......",
        "..FFFFFFF.......",
        "..FFFFFFF.......",
        ".FF.FFFFF.FF....",
        ".F...FFF...F....",
        ".....FFF........",
        ".....FFF........",
        ".....FFF........",
        "................",
        "................",
        "................",
    ],
    3: [  # shield
        "................",
        "....111111......",
        "...1FFFFFF1.....",
        "..1FF111FF1.....",
        "..1FF111FF1.....",
        "..1FF111FF1.....",
        "..1FF111FF1.....",
        "...1FF11FF1.....",
        "...1FF11FF1.....",
        "....1FFFF1......",
        ".....1FF1.......",
        "......11........",
        "................",
        "................",
        "................",
        "................",
    ],
    4: [  # boots (speed)
        "................",
        "......55........",
        "......55........",
        "......55........",
        ".....5555.......",
        "....555555......",
        "...55555555.....",
        "..5555555555....",
        "..1..1111..1....",
        ".11.111111.11...",
        ".11.111111.11...",
        "................",
        "................",
        "................",
        "................",
        "................",
    ],
    5: [  # lightning
        "................",
        ".......FFF......",
        "......FFFFF.....",
        ".....FFFFF......",
        "....FFFFF.......",
        "...FFFFFF.......",
        "..FFFFFF........",
        ".FFFFFF.........",
        "......FFFF......",
        ".....FFFFF......",
        "....FFFFF.......",
        "...FFFFF........",
        "................",
        "................",
        "................",
        "................",
    ],
    6: [  # gear
        "................",
        ".....11111......",
        "....1888881.....",
        "...1811F1181....",
        "..1881FFF1881...",
        "..1881FFF1881...",
        "..1811FFF1181...",
        "...18888881.....",
        "....1888881.....",
        ".....11111......",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
    ],
    7: [  # ring
        "................",
        "................",
        "....1111111.....",
        "...1FFFFFFF1....",
        "..1FF1111FFF1...",
        "..1FF1FFF1FF1...",
        "..1FF1FFF1FF1...",
        "..1FF1111FFF1...",
        "...1FFFFFFF1....",
        "....1111111.....",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
    ],
    9: [  # clock
        "................",
        ".....111111.....",
        "....1FFFFFF1....",
        "...1FF1111FF1...",
        "..1FF111111FF1..",
        "..1FF111111FF1..",
        "..1F11111111F1..",
        "..1F11F11111F1..",
        "..1FF111111FF1..",
        "..1FF111111FF1..",
        "...1FF1111FF1...",
        "....1FFFFFF1....",
        ".....111111.....",
        "................",
        "................",
        "................",
    ],
    10: [  # crown
        "................",
        "................",
        "..1F..1F..1F..1.",
        "..1F..1F..1F..1.",
        "..111111111111..",
        "...FFFFFFFFF....",
        "...FFFFFFFFF....",
        "....FDDDDDF.....",
        "....FFFFFFFF....",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
    ],
    11: [  # arrow up
        "................",
        ".......FF.......",
        "......FFFF......",
        ".....FFFFFF.....",
        "....FFFFFFFF....",
        "......FFFF......",
        "......FFFF......",
        "......FFFF......",
        "......FFFF......",
        "......FFFF......",
        "......FFFF......",
        "................",
        "................",
        "................",
        "................",
        "................",
    ],
    12: [  # gem
        "................",
        "....111111......",
        "...1FFFFFFFF....",
        "..1FFFFFFFFF....",
        ".1FF5555FFFFF...",
        "1FF555555FFFFF..",
        ".1FF5555FFFFF...",
        "..1FFFFFFFFF....",
        "...1FFFFFFFF....",
        "....111111......",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
    ],
    13: [  # skull (unused)
        "................",
        ".....FFFFFF.....",
        "....F11111F.....",
        "...FF1FF1FF.....",
        "...FF1FF1FF.....",
        "...F111111F.....",
        "...FF1111FF.....",
        "....F1111F......",
        "....FFFFFF......",
        ".....F1F1F......",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
    ],
}

# ---------------------------------------------------------------------------
# Art: Explosion fire cross (procedural, geometric, original)
# ---------------------------------------------------------------------------
# 17 groups x 4 frames. Frames grow thin (0) -> thick (3).
# Colors: outer red (RD=9), middle coral (CR=13), core white (WH=15).

def fire_bar_h(t):
    """Horizontal bar, thickness t (rows centered on 7..8)."""
    rows = ['.' * 16 for _ in range(16)]
    r_min = 7 - (t - 1)
    r_max = 8 + (t - 1)
    for r in range(r_min, r_max + 1):
        idx = r - r_min
        color = RD
        if idx >= 2 and idx <= 2 * t - 3:
            color = CR
        if idx >= 3 and idx <= 2 * t - 4:
            color = WH
        rows[r] = hex_c(color) * 16
    return rows


def fire_bar_v(t):
    rows = ['.' * 16 for _ in range(16)]
    c_min = 7 - (t - 1)
    c_max = 8 + (t - 1)
    for r in range(16):
        line = []
        for c in range(16):
            if c_min <= c <= c_max:
                idx = c - c_min
                color = RD
                if idx >= 2 and idx <= 2 * t - 3:
                    color = CR
                if idx >= 3 and idx <= 2 * t - 4:
                    color = WH
                line.append(hex_c(color))
            else:
                line.append('.')
        rows[r] = ''.join(line)
    return rows


def fire_center(t):
    h = fire_bar_h(t)
    v = fire_bar_v(t)
    rows = []
    for r in range(16):
        merged = ''.join(hex_c(WH) if h[r][c] != '.' and v[r][c] != '.' else
                         (h[r][c] if h[r][c] != '.' else v[r][c])
                         for c in range(16))
        rows.append(merged)
    return rows


def fire_tip_h(t, right=True):
    """Horizontal bar with a rounded cap on one end."""
    rows = ['.' * 16 for _ in range(16)]
    r_min = 7 - (t - 1)
    r_max = 8 + (t - 1)
    cap_extra = 1
    cap_range = range(0, 6) if not right else range(10, 16)
    for r in range(r_min, r_max + 1):
        idx = r - r_min
        color = RD
        if idx >= 2 and idx <= 2 * t - 3:
            color = CR
        if idx >= 3 and idx <= 2 * t - 4:
            color = WH
        line = []
        for c in range(16):
            if right:
                if c < 16 - cap_extra and c >= cap_range[0]:
                    line.append(hex_c(color))
                elif c >= 16 - cap_extra:
                    # rounded bulge
                    d = abs(r - 7)
                    if d <= t + 0:
                        line.append(hex_c(RD))
                    else:
                        line.append('.')
                else:
                    line.append('.')
            else:
                if c <= cap_range[-1]:
                    d = abs(r - 7)
                    if d <= t:
                        line.append(hex_c(RD))
                    else:
                        line.append('.')
                elif c < cap_range[-1] + cap_extra + 1:
                    line.append('.')
                else:
                    line.append(hex_c(color))
        rows[r] = ''.join(line)
    return rows


def fire_tip_v(t, down=True):
    v = fire_bar_v(t)
    rows = []
    for r in range(16):
        line = []
        for c in range(16):
            if v[r][c] != '.':
                line.append(v[r][c])
            elif down:
                if r >= 14 - t + 2 and abs(c - 7) <= t:
                    line.append(hex_c(RD))
                else:
                    line.append('.')
            else:
                if r <= t + 1 and abs(c - 7) <= t:
                    line.append(hex_c(RD))
                else:
                    line.append('.')
        rows.append(''.join(line))
    return rows


def hex_c(i):
    return "0123456789ABCDEF"[i]


def gen_explosion_group(kind, t):
    if kind == "CENTER":
        return fire_center(t)
    if kind in ("ARMBASE_HR", "ARNEXT_HR"):
        return fire_bar_h(t)
    if kind in ("ARMBASE_HL", "ARNEXT_HL"):
        return fire_bar_h(t)
    if kind in ("ARMBASE_VD", "ARNEXT_VD"):
        return fire_bar_v(t)
    if kind in ("ARMBASE_VU", "ARNEXT_VU"):
        return fire_bar_v(t)
    if kind == "TIPR":
        return fire_tip_h(t, right=True)
    if kind == "TIPL":
        return fire_tip_h(t, right=False)
    if kind == "TIPD":
        return fire_tip_v(t, down=True)
    if kind == "TIPU":
        return fire_tip_v(t, down=False)
    if kind.startswith("TIP") and kind.endswith("_BASE"):
        base = kind[:-5]
        return gen_explosion_group(base, t)
    raise ValueError(kind)


EXPLOSION_GROUPS = [
    "CENTER",
    "ARMBASE_HR", "ARNEXT_HR",
    "ARMBASE_HL", "ARNEXT_HL",
    "ARMBASE_VD", "ARNEXT_VD",
    "ARMBASE_VU", "ARNEXT_VU",
    "TIPU", "TIPU_BASE",
    "TIPD", "TIPD_BASE",
    "TIPL", "TIPL_BASE",
    "TIPR", "TIPR_BASE",
]


# ---------------------------------------------------------------------------
# Art: Enemy blob (7 walk frames: 3 right + 3 left mirrored + filler; 4 death)
# ---------------------------------------------------------------------------

def blob_rows(eyes_shift=0, squash=0, feet="regular"):
    """squash: 0=normal, 1=flat walk frame, 2=stretch walk frame."""
    if squash == 1:
        rows = [
            "................",
            "................",
            ".....333333.....",
            "....33333333....",
            "...3333333333...",
            "..33FF3333FF33..",
            "..33FF3333FF33..",
            "..333333333333..",
            "..333333333333..",
            "...3322222233...",
            "..332222222233..",
            "..332222222233..",
            "..322222222223..",
            ".3222F2222F2223.",
            ".32222222222223.",
            "................",
        ]
    elif squash == 2:
        rows = [
            "................",
            ".....333333.....",
            "....33333333....",
            "...3333333333...",
            "..333333333333..",
            "..33FF3333FF33..",
            "..33FF3333FF33..",
            "..333333333333..",
            "...3333333333...",
            "...3322222233...",
            "..332222222233..",
            "..322222222223..",
            ".32222222222223.",
            ".3222F2222F2223.",
            "................",
            "................",
        ]
    elif eyes_shift:
        rows = [
            "................",
            ".....333333.....",
            "....33333333....",
            "...3333333333...",
            "..333333333333..",
            "..3FF33333FF333.",
            "..3FF33333FF333.",
            "..333333333333..",
            "...3333333333...",
            "...3322222233...",
            "..332222222233..",
            "..322222222223..",
            ".3222F2222F2223.",
            ".32222222222223.",
            "................",
            "................",
        ]
    else:
        rows = [
            "................",
            ".....333333.....",
            "....33333333....",
            "...3333333333...",
            "..333333333333..",
            "..33FF3333FF33..",
            "..33FF3333FF33..",
            "..333333333333..",
            "...3333333333...",
            "...3322222233...",
            "..332222222233..",
            "..322222222223..",
            ".3222F2222F2223.",
            ".32222222222223.",
            "................",
            "................",
        ]
    return rows


ENEMY_WALK = {
    0: blob_rows(eyes_shift=0, squash=0),
    1: blob_rows(eyes_shift=0, squash=1),
    2: blob_rows(eyes_shift=0, squash=2),
    3: blob_rows(eyes_shift=1, squash=0),
    4: blob_rows(eyes_shift=1, squash=1),
    5: blob_rows(eyes_shift=1, squash=2),
    6: blob_rows(eyes_shift=1, squash=0),  # filler reusing left-facing
}

ENEMY_DEATH = {
    0: blob_rows(eyes_shift=0, squash=0),
    1: blob_rows(eyes_shift=0, squash=1),
    2: [  # shrinking puff
        "................",
        "................",
        "......3333......",
        ".....333333.....",
        ".....33FF33.....",
        ".....333333.....",
        "......3333......",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
    ],
    3: [  # final puff
        "................",
        "................",
        "................",
        ".......33.......",
        ".......33.......",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
    ],
}

# ---------------------------------------------------------------------------
# Art: Player robot (3 walk dirs x 3 frames + 6 death frames)
# ---------------------------------------------------------------------------

def robot_rows(leg=0, arm=0):
    """leg/arm select which walk frame variant. Frames differ in limb pose."""
    if leg == 0:
        rows = [
            "................",
            "......FFFF......",
            ".....FFFFFF.....",
            "....FFFFFFFF....",
            "....F5F5F5FF....",
            "....F5F5F5FF....",
            "....FFFFFFFF....",
            "...FFFFFDFFFF...",
            "...FFFFFDFFFF...",
            "...FFFFFFFFFF...",
            "....FFFFFFFF....",
            "..FF.FDDDDF.FF..",
            "..FF.FDDDDF.FF..",
            "..FF..FFFF..FF..",
            "..FF..F1F1..FF..",
            "................",
        ]
    elif leg == 1:
        rows = [
            "................",
            "......FFFF......",
            ".....FFFFFF.....",
            "....FFFFFFFF....",
            "....F5F5F5FF....",
            "....F5F5F5FF....",
            "....FFFFFFFF....",
            "...FFFFFDFFFF...",
            "...FFFFFDFFFF...",
            "...FFFFFFFFFF...",
            "....FFFFFFFF....",
            "..FF.FDDDDF.FF..",
            ".FFFF.FDDDDF.FF.",
            ".FFF...FFFF..FF.",
            "......F1F1..FF..",
            "................",
        ]
    else:
        rows = [
            "................",
            "......FFFF......",
            ".....FFFFFF.....",
            "....FFFFFFFF....",
            "....F5F5F5FF....",
            "....F5F5F5FF....",
            "....FFFFFFFF....",
            "...FFFFFDFFFF...",
            "...FFFFFDFFFF...",
            "...FFFFFFFFFF...",
            "....FFFFFFFF....",
            "..FF.FDDDDF.FF..",
            "..FF.FDDDDF.FF..",
            "..FF..FFFF..FF..",
            ".FF...F1F1....FF",
            "................",
        ]
    return rows


def robot_up_rows(leg=0):
    """Back view: antenna on top instead of visor."""
    if leg == 1:
        rows = [
            "................",
            "......F1F.......",
            ".......FFF......",
            "....FFFFFFFF....",
            "....F5F5F5FF....",
            "....F5F5F5FF....",
            "....FFFFFFFF....",
            "...FFFFFDFFFF...",
            "...FFFFFDFFFF...",
            "...FFFFFFFFFF...",
            "....FFFFFFFF....",
            "..FF.FDDDDF.FF..",
            ".FFFF.FDDDDF.FF.",
            "..FF..FFFF..FF..",
            "......F1F1..FF..",
            "................",
        ]
    elif leg == 2:
        rows = [
            "................",
            "......F1F.......",
            ".......FFF......",
            "....FFFFFFFF....",
            "....F5F5F5FF....",
            "....F5F5F5FF....",
            "....FFFFFFFF....",
            "...FFFFFDFFFF...",
            "...FFFFFDFFFF...",
            "...FFFFFFFFFF...",
            "....FFFFFFFF....",
            "..FF.FDDDDF.FF..",
            "..FF.FDDDDF.FF..",
            "..FF..FFFF..FF..",
            ".FF...F1F1....FF",
            "................",
        ]
    else:
        rows = [
            "................",
            "......F1F.......",
            ".......FFF......",
            "....FFFFFFFF....",
            "....F5F5F5FF....",
            "....F5F5F5FF....",
            "....FFFFFFFF....",
            "...FFFFFDFFFF...",
            "...FFFFFDFFFF...",
            "...FFFFFFFFFF...",
            "....FFFFFFFF....",
            "..FF.FDDDDF.FF..",
            "..FF.FDDDDF.FF..",
            "..FF..FFFF..FF..",
            "..FF........FF..",
            "................",
        ]
    return rows


def robot_right_rows(leg=0):
    """Side view: visor band to the right, one arm raised."""
    if leg == 1:
        rows = [
            "................",
            "......FFFF......",
            ".....FFFFFFF....",
            "....FFFFFFFFF...",
            "....F5F5F5FFF...",
            "....F5F5F5FFF...",
            "....FFFFFFFFF...",
            "...FFFFFDFFFF...",
            "...FFFFFDFFF....",
            "...FFFFFFFFFF...",
            "....FFFFFFFF....",
            "..FF.FDDDDF.FF..",
            ".FFFF.FDDDDF.FF.",
            "..FF..FFFF..FF..",
            "......F1F1..FF..",
            "................",
        ]
    elif leg == 2:
        rows = [
            "................",
            "......FFFF......",
            ".....FFFFFFF....",
            "....FFFFFFFFF...",
            "....F5F5F5FFF...",
            "....F5F5F5FFF...",
            "....FFFFFFFFF...",
            "...FFFFFDFFFF...",
            "...FFFFFDFFF....",
            "...FFFFFFFFFF...",
            "....FFFFFFFF....",
            "..FF.FDDDDF.FF..",
            "..FF.FDDDDF.FF..",
            "..FF..FFFF..FF..",
            ".FF...F1F1....FF",
            "................",
        ]
    else:
        rows = [
            "................",
            "......FFFF......",
            ".....FFFFFFF....",
            "....FFFFFFFFF...",
            "....F5F5F5FFF...",
            "....F5F5F5FFF...",
            "....FFFFFFFFF...",
            "...FFFFFDFFFF...",
            "...FFFFFDFFF....",
            "...FFFFFFFFFF...",
            "....FFFFFFFF....",
            "..FF.FDDDDF.FF..",
            "..FF.FDDDDF.FF..",
            "..FF..FFFF..FF..",
            "..FF........FF..",
            "................",
        ]
    return rows


def robot_death_rows(step):
    if step == 0:
        rows = [
            "................",
            "......FFFF......",
            ".....FFFFFF.....",
            "....FFFFFFFF....",
            "....F5F5F5FF....",
            "....F5F5F5FF....",
            "....FFFFFFFF....",
            "...FFFFFDFFFF...",
            "...FFFFFDFFFF...",
            "...FFFFFFFFFF...",
            "....FFFFFFFF....",
            "..FF.FDDDDF.FF..",
            "..FF.FDDDDF.FF..",
            "..FF..FFFF..FF..",
            "..FF..F1F1..FF..",
            "................",
        ]
    elif step == 1:
        rows = [
            "................",
            "......FFFF......",
            ".....FFFFFF.....",
            "....FFFFFFFF....",
            "....F5F5F5FF....",
            "....F5F5F5FF....",
            "....FFFFFFFF....",
            "...FFFFFDFFFF...",
            "...FFFFFDFFFF...",
            "...FFFFFFFFFF...",
            "....FFFFFFFF....",
            "..FF.FDDDDF.FF..",
            "..FF.FDDDDF.FF..",
            "..FF..FFFF..FF..",
            "..FF........FF..",
            "................",
        ]
    elif step == 2:
        rows = [
            "................",
            "......FFFF......",
            ".....FFFFFF.....",
            "....FFFFFFFF....",
            "....F5F5F5FF....",
            "....F5F5F5FF....",
            "....FFFFFFFF....",
            "...FFFFFDFFFF...",
            "...FFFFFDFFFF...",
            "...FFFFFFFFFF...",
            "....FFFFFFFF....",
            "..FF.FDDDDF.FF..",
            "..FF.FDDDDF.FF..",
            "..FF..FFFF..FF..",
            "................",
            "................",
        ]
    elif step == 3:
        rows = [
            "................",
            "......FFFF......",
            ".....FFFFFF.....",
            "....FFFFFFFF....",
            "....F5F5F5FF....",
            "....F5F5F5FF....",
            "....FFFFFFFF....",
            "...FFFFFDFFFF...",
            "...FFFFFDFFFF...",
            "...FFFFFFFFFF...",
            "....FFFFFFFF....",
            "..FF.FDDDDF.FF..",
            "..FF.FDDDDF.FF..",
            "................",
            "................",
            "................",
        ]
    elif step == 4:
        rows = [
            "................",
            "......FFFF......",
            ".....FFFFFF.....",
            "....FFFFFFFF....",
            "....F5F5F5FF....",
            "....F5F5F5FF....",
            "....FFFFFFFF....",
            "...FFFFFDFFFF...",
            "...FFFFFFFFFF...",
            "....FFFFFFFF....",
            "..FF.FDDDDF.FF..",
            "..FF.FDDDDF.FF..",
            "................",
            "................",
            "................",
            "................",
        ]
    else:
        rows = [
            "................",
            "......FFFF......",
            ".....FFFFFF.....",
            "....FFFFFFFF....",
            "....F5F5F5FF....",
            "....FFFFFFFF....",
            "..FF.FDDDDF.FF..",
            "..FF.FDDDDF.FF..",
            "................",
            "................",
            "................",
            "................",
            "................",
            "................",
            "................",
            "................",
        ]
    return rows


PLAYER_WALK_DOWN = {0: robot_rows(leg=0), 1: robot_rows(leg=1), 2: robot_rows(leg=2)}
PLAYER_WALK_UP = {0: robot_up_rows(0), 1: robot_up_rows(1), 2: robot_up_rows(2)}
PLAYER_WALK_RIGHT = {0: robot_right_rows(0), 1: robot_right_rows(1), 2: robot_right_rows(2)}

PLAYER_DEATH = {
    0: robot_death_rows(0),
    1: robot_death_rows(1),
    2: robot_death_rows(2),
    3: robot_death_rows(3),
    4: robot_death_rows(4),
    5: robot_death_rows(5),
}


# ---------------------------------------------------------------------------
# Header writers
# ---------------------------------------------------------------------------

def write_bomb():
    lines = [HEADER_HEAD,
             "// Bomb pulse cycle: 3 original CC0 frames. Black body (1) with a",
             "// white highlight (F) and a moving fuse spark (D/F).",
             ""]
    for name in ("BOMB_FRAME_0_4BPP", "BOMB_FRAME_1_4BPP", "BOMB_FRAME_2_4BPP"):
        lines += fmt_array(name, pack(BOMB[name]))
        lines.append("")
    lines += fmt_sprite4_arr("kBombSprites",
                             ["BOMB_FRAME_0_4BPP", "BOMB_FRAME_1_4BPP", "BOMB_FRAME_2_4BPP"],
                             "3-frame pulse cycle")
    lines.append(HEADER_TAIL)
    write("BombSprites.h", lines)


def write_tiles():
    lines = [HEADER_HEAD,
             "// Original CC0 board tiles: hard wall (brick), soft wall (crate),",
             "// exit door, and 14 power-up icons.",
             ""]
    tiles = [
        ("HARD_WALL_4BPP", HARD_WALL),
        ("SOFT_WALL_4BPP", SOFT_WALL),
        ("EXIT_4BPP", EXIT),
        ("POWERUP_FIRE_4BPP", POWERUP_FIRE),
        ("POWERUP_BOMB_4BPP", POWERUP_BOMB),
    ]
    for name, art in tiles:
        lines += fmt_array(name, pack(art))
        lines.append("")
    lines += fmt_sprite4("kHardWallSprite", "HARD_WALL_4BPP", PALETTE_MAP, "hard wall tile")
    lines += fmt_sprite4("kSoftWallSprite", "SOFT_WALL_4BPP", PALETTE_MAP, "shared soft-wall tile (all 3 variants)")
    lines += fmt_sprite4("kExitSprite", "EXIT_4BPP", PALETTE_MAP, "exit door")
    lines += fmt_sprite4("kPowerUpFireSprite", "POWERUP_FIRE_4BPP", PALETTE_MAP, "fire power-up")
    lines += fmt_sprite4("kPowerUpBombSprite", "POWERUP_BOMB_4BPP", PALETTE_MAP, "bomb power-up")
    lines.append("")
    # Full power-up sheet (14 original icons)
    for i in range(14):
        art = POWERUP_ALL.get(i)
        if art is None:
            art = POWERUP_FIRE  # fallback, never happens (all defined)
        lines += fmt_array(f"POWERUP_ALL_{i}_4BPP", pack(art))
        lines.append("")
    entries = [f"POWERUP_ALL_{i}_4BPP" for i in range(14)]
    lines += fmt_sprite4_arr("kPowerUpsAll", entries, "full 14-icon power-up sheet")
    lines.append(HEADER_TAIL)
    write("BoardTiles.h", lines)


def write_explosion():
    lines = [HEADER_HEAD,
             "// Original CC0 fire-cross explosion. 17 groups x 4 frames (thin->thick).",
             "// Colors: red outline (9), coral body (D), white core (F).",
             ""]
    arrays = {}
    for group in EXPLOSION_GROUPS:
        for f in range(4):
            t = f + 1
            name = f"EXPLOSION_{group}_{f}_4BPP"
            arrays[name] = pack(gen_explosion_group(group, t))
            lines += fmt_array(name, arrays[name], f"{group} frame {f} (thickness {t})")
            lines.append("")
    lines += fmt_sprite4_arr("kCENTER", [f"EXPLOSION_CENTER_{f}_4BPP" for f in range(4)], "center")
    for group in ("ARMBASE_HR", "ARNEXT_HR", "ARMBASE_HL", "ARNEXT_HL",
                  "ARMBASE_VD", "ARNEXT_VD", "ARMBASE_VU", "ARNEXT_VU",
                  "TIPU", "TIPU_BASE", "TIPD", "TIPD_BASE",
                  "TIPL", "TIPL_BASE", "TIPR", "TIPR_BASE"):
        lines += fmt_sprite4_arr(f"k{group}", [f"EXPLOSION_{group}_{f}_4BPP" for f in range(4)], group)
        lines.append("")
    lines.append(HEADER_TAIL)
    write("ExplosionSprites.h", lines)


def write_enemy():
    lines = [HEADER_HEAD,
             "// Original CC0 enemy blob: green slime with white eyes.",
             "// 7 walk frames (3 right + 3 left + 1 filler) and 4 death frames.",
             ""]
    for i in range(7):
        lines += fmt_array(f"ENEMY_SLIME_WALK_{i}_4BPP", pack(ENEMY_WALK[i]),
                           f"walk frame {i}")
        lines.append("")
    for i in range(4):
        lines += fmt_array(f"ENEMY_SLIME_DEATH_{i}_4BPP", pack(ENEMY_DEATH[i]),
                           f"death frame {i}")
        lines.append("")
    walk_entries = [f"ENEMY_SLIME_WALK_{i}_4BPP" for i in range(7)]
    death_entries = [f"ENEMY_SLIME_DEATH_{i}_4BPP" for i in range(4)]
    lines += fmt_sprite4_arr("kEnemySlimeWalk", walk_entries, "7-frame walk")
    lines += fmt_sprite4_arr("kEnemySlimeDeath", death_entries, "4-frame death")
    lines.append(HEADER_TAIL)
    write("EnemySprites.h", lines)


def write_player():
    lines = [HEADER_HEAD,
             "// Original CC0 player robot: white body, light-blue visor, coral hands.",
             "// 3 walk frames per direction (Down/Up/Right; Left mirrors Right via",
             "// flipX at draw time) plus 6 death frames.",
             ""]
    groups = [
        ("PLAYER_WALK_DOWN", PLAYER_WALK_DOWN, "kPlayerWalkDown", 3),
        ("PLAYER_WALK_UP", PLAYER_WALK_UP, "kPlayerWalkUp", 3),
        ("PLAYER_WALK_RIGHT", PLAYER_WALK_RIGHT, "kPlayerWalkRight", 3),
        ("PLAYER_DEATH", PLAYER_DEATH, "kPlayerDeath", 6),
    ]
    arrays = {}
    for prefix, data, sym, n in groups:
        for i in range(n):
            name = f"{prefix}_{i}_4BPP"
            arrays[name] = pack(data[i])
            lines += fmt_array(name, arrays[name], f"{prefix} frame {i}")
            lines.append("")
    for prefix, data, sym, n in groups:
        entries = [f"{prefix}_{i}_4BPP" for i in range(n)]
        lines += fmt_sprite4_arr(sym, entries, sym)
        lines.append("")
    lines.append(HEADER_TAIL)
    write("PlayerSprites.h", lines)


def write(name, lines):
    path = os.path.join(ASSETS, name)
    os.makedirs(ASSETS, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"wrote {path}")


def main():
    write_bomb()
    write_tiles()
    write_explosion()
    write_enemy()
    write_player()


if __name__ == "__main__":
    main()
