#pragma once

// Generated by PixelRoot32 Tool Suite — SFX Editor
// Requires game-defined enum class SfxId.
//
// Dispatch recommendation (game-side):
//   Preferred: playSfxBank<SfxBank>(audioEngine, id, delayScheduler);
//     (PixelRoot32 Engine: include/audio/SfxBankPlayback.h)
//   Manual equivalent:
//     1) For i in [0, layerCount(id)): playEvent(layerEvent(id, i)) at t=0
//     2) For i in [0, sequenceStepCount(id)):
//          auto step = sequenceStep(id, i);
//          schedule playEvent(step.event) at now + step.delaySec
// Continuous (loop=true) voices stay on until STOP_CHANNEL (or steal).
// duration==0 with loop=false is invalid one-shot data — do not rely on it.

#include <audio/AudioTypes.h>
#include <audio/AudioMusicTypes.h>
#include <cstdint>
#include "audio/AudioDirector.h"

namespace bomberbot {

namespace sfx_presets {

using pixelroot32::audio::InstrumentPreset;
using pixelroot32::audio::LfoTarget;

static constexpr InstrumentPreset INSTR_SFX_SFX_ENV_PULSE_BLIP{
    0.850000024f, 0.5f, 4, 0.0f, 0,
    0.00100000005f, 0.0399999991f, 0.150000006f, 0.0399999991f,
    LfoTarget::NONE, 0.0f, 0.0f, 0.0f, false, 0.0f, 0.0f, 0.0f
};

static constexpr InstrumentPreset INSTR_SFX_SFX_ENV_NOISE_BOOM{
    0.850000024f, 0.5f, 4, 0.0f, 20,
    0.00100000005f, 0.119999997f, 0.0f, 0.100000001f,
    LfoTarget::NONE, 0.0f, 0.0f, 0.0f, false, 0.0f, 0.0f, 0.0f
};

static constexpr InstrumentPreset INSTR_SFX_SFX_ENV_TRIANGLE_SOFT{
    0.75f, 0.5f, 4, 0.0f, 0,
    0.00200000009f, 0.0799999982f, 0.349999994f, 0.0799999982f,
    LfoTarget::NONE, 0.0f, 0.0f, 0.0f, false, 0.0f, 0.0f, 0.0f
};

static constexpr InstrumentPreset INSTR_SFX_SFX_ENV_PULSE_SWEEP{
    0.800000012f, 0.25f, 4, 0.0f, 0,
    0.00100000005f, 0.0500000007f, 0.100000001f, 0.0500000007f,
    LfoTarget::NONE, 0.0f, 0.0f, 0.0f, false, 0.0f, 0.0f, 0.0f
};

static constexpr InstrumentPreset INSTR_SFX_SFX_ENV_NOISE_HIT{
    0.699999988f, 0.5f, 4, 0.0f, 40,
    0.00100000005f, 0.0299999993f, 0.0500000007f, 0.0399999991f,
    LfoTarget::NONE, 0.0f, 0.0f, 0.0f, true, 0.0f, 0.0f, 0.0f
};

} // namespace sfx_presets

using pixelroot32::audio::SfxBreakpoint;

/// Game-owned SFX ids — must match exported SfxBank.cppSymbol cases.
enum class SfxId : uint8_t {
    PlaceBomb,
    Death,
    CoinBlip,
    MenuBlip,
    StageClear,
    PickupPowerSoft,
    BombExplosionTiny,
    EnemyDeath,
    Footstep,
    FootstepSoft,
    Count
};

struct SfxBank {
    struct SequenceStep {
        float delaySec;
        pixelroot32::audio::AudioEvent event;
    };

    static constexpr unsigned long cooldownMs(SfxId id) {
        switch (id) {
            case SfxId::PlaceBomb:
                return 0;
            case SfxId::Death:
                return 0;
            case SfxId::CoinBlip:
                return 0;
            case SfxId::MenuBlip:
                return 0;
            case SfxId::StageClear:
                return 0;
            case SfxId::PickupPowerSoft:
                return 0;
            case SfxId::BombExplosionTiny:
                return 0;
            case SfxId::EnemyDeath:
                return 0;
            case SfxId::Footstep:
                return 0;
            case SfxId::FootstepSoft:
                return 0;
            default:
                return 0;
        }
    }

    static constexpr uint8_t layerCount(SfxId id) {
        switch (id) {
            case SfxId::PlaceBomb:
                return 1;
            case SfxId::Death:
                return 1;
            case SfxId::CoinBlip:
                return 0;
            case SfxId::MenuBlip:
                return 1;
            case SfxId::StageClear:
                return 0;
            case SfxId::PickupPowerSoft:
                return 0;
            case SfxId::BombExplosionTiny:
                return 2;
            case SfxId::EnemyDeath:
                return 2;
            case SfxId::Footstep:
                return 1;
            case SfxId::FootstepSoft:
                return 1;
            default:
                return 1;
        }
    }

    static constexpr uint8_t sequenceStepCount(SfxId id) {
        switch (id) {
            case SfxId::PlaceBomb:
                return 0;
            case SfxId::Death:
                return 4;
            case SfxId::CoinBlip:
                return 3;
            case SfxId::MenuBlip:
                return 0;
            case SfxId::StageClear:
                return 6;
            case SfxId::PickupPowerSoft:
                return 4;
            case SfxId::BombExplosionTiny:
                return 0;
            case SfxId::EnemyDeath:
                return 0;
            case SfxId::Footstep:
                return 0;
            case SfxId::FootstepSoft:
                return 0;
            default:
                return 0;
        }
    }

    static constexpr pixelroot32::audio::AudioEvent layerEvent(SfxId id, uint8_t layerIndex) {
        using namespace pixelroot32::audio;
        using namespace sfx_presets;

        switch (id) {
            case SfxId::PlaceBomb:
                if (layerIndex == 0) {
                    return {
                        WaveType::PULSE,
                        360.0f,
                        0.0799999982f,
                        0.419999987f,
                        0.5f,
                        0,
                        &INSTR_SFX_SFX_ENV_PULSE_BLIP,
                        180.0f,
                        0.0599999987f,
                        false,
                        SweepCurve::Linear,
                        nullptr,
                        0,
                        nullptr,
                        0
                    };
                }
                break;
            case SfxId::Death:
                if (layerIndex == 0) {
                    return {
                        WaveType::NOISE,
                        500.0f,
                        0.159999996f,
                        0.349999994f,
                        0.5f,
                        40,
                        &INSTR_SFX_SFX_ENV_NOISE_HIT,
                        0.0f,
                        0.0f,
                        false,
                        SweepCurve::Linear,
                        nullptr,
                        0,
                        nullptr,
                        0
                    };
                }
                break;
            case SfxId::CoinBlip:
                break;
            case SfxId::MenuBlip:
                if (layerIndex == 0) {
                    return {
                        WaveType::PULSE,
                        880.0f,
                        0.0500000007f,
                        0.400000006f,
                        0.25f,
                        0,
                        &INSTR_SFX_SFX_ENV_PULSE_BLIP,
                        0.0f,
                        0.0f,
                        false,
                        SweepCurve::Linear,
                        nullptr,
                        0,
                        nullptr,
                        0
                    };
                }
                break;
            case SfxId::StageClear:
                break;
            case SfxId::PickupPowerSoft:
                break;
            case SfxId::BombExplosionTiny:
                if (layerIndex == 0) {
                    return {
                        WaveType::NOISE,
                        480.000031f,
                        1.10000002f,
                        0.487499982f,
                        0.5f,
                        18,
                        &INSTR_SFX_SFX_ENV_NOISE_BOOM,
                        96.0f,
                        0.899999976f,
                        false,
                        SweepCurve::Linear,
                        nullptr,
                        0,
                        nullptr,
                        0
                    };
                }
                if (layerIndex == 1) {
                    return {
                        WaveType::TRIANGLE,
                        156.972f,
                        0.649999976f,
                        0.25999999f,
                        0.5f,
                        0,
                        &INSTR_SFX_SFX_ENV_TRIANGLE_SOFT,
                        39.2400017f,
                        0.550000012f,
                        false,
                        SweepCurve::Linear,
                        nullptr,
                        0,
                        nullptr,
                        0
                    };
                }
                break;
            case SfxId::EnemyDeath:
                if (layerIndex == 0) {
                    return {
                        WaveType::NOISE,
                        1100.0f,
                        0.140000001f,
                        0.231000006f,
                        0.5f,
                        22,
                        &INSTR_SFX_SFX_ENV_NOISE_BOOM,
                        200.0f,
                        0.119999997f,
                        false,
                        SweepCurve::Linear,
                        nullptr,
                        0,
                        nullptr,
                        0
                    };
                }
                if (layerIndex == 1) {
                    return {
                        WaveType::PULSE,
                        330.0f,
                        0.100000001f,
                        0.319999993f,
                        0.5f,
                        0,
                        &INSTR_SFX_SFX_ENV_PULSE_BLIP,
                        110.0f,
                        0.0799999982f,
                        false,
                        SweepCurve::Linear,
                        nullptr,
                        0,
                        nullptr,
                        0
                    };
                }
                break;
            case SfxId::Footstep:
                if (layerIndex == 0) {
                    return {
                        WaveType::NOISE,
                        320.0f,
                        0.0399999991f,
                        0.379999995f,
                        0.5f,
                        50,
                        &INSTR_SFX_SFX_ENV_NOISE_HIT,
                        0.0f,
                        0.0f,
                        false,
                        SweepCurve::Linear,
                        nullptr,
                        0,
                        nullptr,
                        0
                    };
                }
                break;
            case SfxId::FootstepSoft:
                if (layerIndex == 0) {
                    return {
                        WaveType::NOISE,
                        320.0f,
                        0.0500000007f,
                        0.300000012f,
                        0.5f,
                        50,
                        &INSTR_SFX_SFX_ENV_NOISE_HIT,
                        180.0f,
                        0.0299999993f,
                        false,
                        SweepCurve::Linear,
                        nullptr,
                        0,
                        nullptr,
                        0
                    };
                }
                break;
            default:
                break;
        }
        return {WaveType::PULSE, 0.0f, 0.0f, 0.0f, 0.5f};
    }

    static constexpr SequenceStep sequenceStep(SfxId id, uint8_t stepIndex) {
        using namespace pixelroot32::audio;
        using namespace sfx_presets;

        switch (id) {
            case SfxId::PlaceBomb:
                break;
            case SfxId::Death:
                if (stepIndex == 0) {
                    return {
                        0.0f,
                        {
                            WaveType::PULSE,
                            523.25f,
                            0.0799999982f,
                            0.449999988f,
                            0.25f,
                            0,
                            &INSTR_SFX_SFX_ENV_PULSE_BLIP,
                            0.0f,
                            0.0f,
                            false,
                            SweepCurve::Linear,
                            nullptr,
                            0,
                            nullptr,
                            0
                        }
                    };
                }
                if (stepIndex == 1) {
                    return {
                        0.0700000003f,
                        {
                            WaveType::PULSE,
                            392.0f,
                            0.0799999982f,
                            0.419999987f,
                            0.25f,
                            0,
                            &INSTR_SFX_SFX_ENV_PULSE_BLIP,
                            0.0f,
                            0.0f,
                            false,
                            SweepCurve::Linear,
                            nullptr,
                            0,
                            nullptr,
                            0
                        }
                    };
                }
                if (stepIndex == 2) {
                    return {
                        0.140000001f,
                        {
                            WaveType::PULSE,
                            329.630005f,
                            0.0900000036f,
                            0.400000006f,
                            0.5f,
                            0,
                            &INSTR_SFX_SFX_ENV_PULSE_BLIP,
                            0.0f,
                            0.0f,
                            false,
                            SweepCurve::Linear,
                            nullptr,
                            0,
                            nullptr,
                            0
                        }
                    };
                }
                if (stepIndex == 3) {
                    return {
                        0.219999999f,
                        {
                            WaveType::PULSE,
                            261.630005f,
                            0.119999997f,
                            0.379999995f,
                            0.5f,
                            0,
                            &INSTR_SFX_SFX_ENV_PULSE_SWEEP,
                            130.809998f,
                            0.100000001f,
                            false,
                            SweepCurve::Linear,
                            nullptr,
                            0,
                            nullptr,
                            0
                        }
                    };
                }
                break;
            case SfxId::CoinBlip:
                if (stepIndex == 0) {
                    return {
                        0.0f,
                        {
                            WaveType::PULSE,
                            1046.5f,
                            0.0450000018f,
                            0.449999988f,
                            0.5f,
                            0,
                            &INSTR_SFX_SFX_ENV_PULSE_BLIP,
                            0.0f,
                            0.0f,
                            false,
                            SweepCurve::Linear,
                            nullptr,
                            0,
                            nullptr,
                            0
                        }
                    };
                }
                if (stepIndex == 1) {
                    return {
                        0.0250000004f,
                        {
                            WaveType::PULSE,
                            1318.5f,
                            0.0450000018f,
                            0.439999998f,
                            0.5f,
                            0,
                            &INSTR_SFX_SFX_ENV_PULSE_BLIP,
                            0.0f,
                            0.0f,
                            false,
                            SweepCurve::Linear,
                            nullptr,
                            0,
                            nullptr,
                            0
                        }
                    };
                }
                if (stepIndex == 2) {
                    return {
                        0.0500000007f,
                        {
                            WaveType::PULSE,
                            1568.0f,
                            0.0549999997f,
                            0.419999987f,
                            0.5f,
                            0,
                            &INSTR_SFX_SFX_ENV_PULSE_BLIP,
                            0.0f,
                            0.0f,
                            false,
                            SweepCurve::Linear,
                            nullptr,
                            0,
                            nullptr,
                            0
                        }
                    };
                }
                break;
            case SfxId::MenuBlip:
                break;
            case SfxId::StageClear:
                if (stepIndex == 0) {
                    return {
                        0.0f,
                        {
                            WaveType::PULSE,
                            523.25f,
                            0.0799999982f,
                            0.419999987f,
                            0.5f,
                            0,
                            &INSTR_SFX_SFX_ENV_PULSE_BLIP,
                            0.0f,
                            0.0f,
                            false,
                            SweepCurve::Linear,
                            nullptr,
                            0,
                            nullptr,
                            0
                        }
                    };
                }
                if (stepIndex == 1) {
                    return {
                        0.0799999982f,
                        {
                            WaveType::PULSE,
                            659.25f,
                            0.0799999982f,
                            0.400000006f,
                            0.5f,
                            0,
                            &INSTR_SFX_SFX_ENV_PULSE_BLIP,
                            0.0f,
                            0.0f,
                            false,
                            SweepCurve::Linear,
                            nullptr,
                            0,
                            nullptr,
                            0
                        }
                    };
                }
                if (stepIndex == 2) {
                    return {
                        0.159999996f,
                        {
                            WaveType::PULSE,
                            783.98999f,
                            0.0799999982f,
                            0.379999995f,
                            0.25f,
                            0,
                            &INSTR_SFX_SFX_ENV_PULSE_BLIP,
                            0.0f,
                            0.0f,
                            false,
                            SweepCurve::Linear,
                            nullptr,
                            0,
                            nullptr,
                            0
                        }
                    };
                }
                if (stepIndex == 3) {
                    return {
                        0.239999995f,
                        {
                            WaveType::PULSE,
                            1046.5f,
                            0.0799999982f,
                            0.400000006f,
                            0.25f,
                            0,
                            &INSTR_SFX_SFX_ENV_PULSE_BLIP,
                            0.0f,
                            0.0f,
                            false,
                            SweepCurve::Linear,
                            nullptr,
                            0,
                            nullptr,
                            0
                        }
                    };
                }
                if (stepIndex == 4) {
                    return {
                        0.319999993f,
                        {
                            WaveType::PULSE,
                            1318.5f,
                            0.0799999982f,
                            0.379999995f,
                            0.25f,
                            0,
                            &INSTR_SFX_SFX_ENV_PULSE_BLIP,
                            0.0f,
                            0.0f,
                            false,
                            SweepCurve::Linear,
                            nullptr,
                            0,
                            nullptr,
                            0
                        }
                    };
                }
                if (stepIndex == 5) {
                    return {
                        0.400000006f,
                        {
                            WaveType::PULSE,
                            1568.0f,
                            0.119999997f,
                            0.419999987f,
                            0.125f,
                            0,
                            &INSTR_SFX_SFX_ENV_PULSE_BLIP,
                            0.0f,
                            0.0f,
                            false,
                            SweepCurve::Linear,
                            nullptr,
                            0,
                            nullptr,
                            0
                        }
                    };
                }
                break;
            case SfxId::PickupPowerSoft:
                if (stepIndex == 0) {
                    return {
                        0.0f,
                        {
                            WaveType::PULSE,
                            481.390015f,
                            0.0799999982f,
                            0.340000004f,
                            0.25f,
                            0,
                            &INSTR_SFX_SFX_ENV_PULSE_BLIP,
                            0.0f,
                            0.0f,
                            false,
                            SweepCurve::Linear,
                            nullptr,
                            0,
                            nullptr,
                            0
                        }
                    };
                }
                if (stepIndex == 1) {
                    return {
                        0.0299999993f,
                        {
                            WaveType::PULSE,
                            606.51001f,
                            0.0799999982f,
                            0.323000014f,
                            0.25f,
                            0,
                            &INSTR_SFX_SFX_ENV_PULSE_BLIP,
                            0.0f,
                            0.0f,
                            false,
                            SweepCurve::Linear,
                            nullptr,
                            0,
                            nullptr,
                            0
                        }
                    };
                }
                if (stepIndex == 2) {
                    return {
                        0.0599999987f,
                        {
                            WaveType::PULSE,
                            721.270813f,
                            0.0799999982f,
                            0.306000024f,
                            0.25f,
                            0,
                            &INSTR_SFX_SFX_ENV_PULSE_BLIP,
                            0.0f,
                            0.0f,
                            false,
                            SweepCurve::Linear,
                            nullptr,
                            0,
                            nullptr,
                            0
                        }
                    };
                }
                if (stepIndex == 3) {
                    return {
                        0.0900000036f,
                        {
                            WaveType::PULSE,
                            962.780029f,
                            0.119999997f,
                            0.340000004f,
                            0.125f,
                            0,
                            &INSTR_SFX_SFX_ENV_PULSE_SWEEP,
                            1213.02002f,
                            0.0799999982f,
                            false,
                            SweepCurve::Linear,
                            nullptr,
                            0,
                            nullptr,
                            0
                        }
                    };
                }
                break;
            case SfxId::BombExplosionTiny:
                break;
            case SfxId::EnemyDeath:
                break;
            case SfxId::Footstep:
                break;
            case SfxId::FootstepSoft:
                break;
            default:
                break;
        }
        return {0.0f, {WaveType::PULSE, 0.0f, 0.0f, 0.0f, 0.5f}};
    }

    static constexpr pixelroot32::audio::AudioEvent eventFor(SfxId id) {
        return layerEvent(id, 0);
    }
};

} // namespace bomberbot
