#ifndef ROOMSCREEN_MAIN_SCENE_H
#define ROOMSCREEN_MAIN_SCENE_H

#include <graphics/Renderer.h>
#include <physics/TileAttributes.h>
#include <gameplay/RoomLayout.h>
#include <stdint.h>
#include <string.h>

// PROGMEM compatibility macros are now provided by Renderer.h

/**
 * PixelRoot32 Exported Scene: RoomScreen - Main Scene
 * Generated by PixelRoot32 Tilemap Editor
 */

// Multi-palette mode: palette definitions and PALETTE_MAPPING are in the namespace below

namespace roomscreen::main_scene {

    // --- Palette Definitions ---
    // Multi-palette mode: one palette per slot, named after the first layer using that slot

    // Palette for Background (slot 0)
    static const uint16_t PIXELROOT32_SCENE_FLASH_ATTR BACKGROUND_PALETTE[16] = {
        0x0000, // 0: RGB(0, 0, 0) - Transparent
        0x2C0F, // 1: RGB(42, 131, 121) - green
        0x62F2, // 2: RGB(99, 93, 150) - blue
        0x654B, // 3: RGB(102, 170, 93) - orange
        0x9C7C, // 4: RGB(154, 143, 224) - purple
        0xA431, // 5: RGB(166, 133, 143) - peach/salmon
        0xB68F, // 6: RGB(176, 208, 126) - green
        0xC63D, // 7: RGB(196, 199, 238) - purple
        0xCDD5, // 8: RGB(205, 187, 171) - peach/salmon
        0xFFFF, // 9: RGB(252, 252, 252) - white
        0xFF15, // 10: RGB(255, 227, 174) - peach/salmon
        0x0000, 0x0000, 0x0000, 0x0000, 0x0000
    };

    // Palette for Items (slot 1)
    static const uint16_t PIXELROOT32_SCENE_FLASH_ATTR ITEMS_PALETTE[16] = {
        0x0000, // 0: RGB(0, 0, 0) - Transparent
        0x18E6, // 1: RGB(27, 29, 52) - blue
        0x1AAB, // 2: RGB(28, 86, 89) - blue
        0x296C, // 3: RGB(41, 47, 101) - blue
        0x2C0F, // 4: RGB(42, 131, 121) - green
        0x62F2, // 5: RGB(99, 93, 150) - blue
        0x654B, // 6: RGB(102, 170, 93) - orange
        0x924D, // 7: RGB(150, 73, 104) - red
        0x9C7C, // 8: RGB(154, 143, 224) - purple
        0xA431, // 9: RGB(166, 133, 143) - peach/salmon
        0xB68F, // 10: RGB(176, 208, 126) - green
        0xC63D, // 11: RGB(196, 199, 238) - purple
        0xCDD5, // 12: RGB(205, 187, 171) - peach/salmon
        0xFFFF, // 13: RGB(252, 252, 252) - white
        0xFF15, // 14: RGB(255, 227, 174) - peach/salmon
        0x0000
    };

    // Palette for Details (slot 2)
    static const uint16_t PIXELROOT32_SCENE_FLASH_ATTR DETAILS_PALETTE[16] = {
        0x0000, // 0: RGB(0, 0, 0) - Transparent
        0x18E6, // 1: RGB(27, 29, 52) - blue
        0x1AAB, // 2: RGB(28, 86, 89) - blue
        0x296C, // 3: RGB(41, 47, 101) - blue
        0x2C0F, // 4: RGB(42, 131, 121) - green
        0x62F2, // 5: RGB(99, 93, 150) - blue
        0x654B, // 6: RGB(102, 170, 93) - orange
        0x9C7C, // 7: RGB(154, 143, 224) - purple
        0xB68F, // 8: RGB(176, 208, 126) - green
        0xC63D, // 9: RGB(196, 199, 238) - purple
        0xCDD5, // 10: RGB(205, 187, 171) - peach/salmon
        0xE438, // 11: RGB(230, 135, 197) - peach/salmon
        0xFFFF, // 12: RGB(252, 252, 252) - white
        0xFDB0, // 13: RGB(255, 180, 130) - peach/salmon
        0xFDDC, // 14: RGB(255, 186, 225) - peach/salmon
        0xFF15, // 15: RGB(255, 227, 174) - peach/salmon
    };

    // Color index mapping for tileset sprites (shared in multi-palette mode)
    static const pixelroot32::graphics::Color PIXELROOT32_SCENE_FLASH_ATTR PALETTE_MAPPING[] = {
        (pixelroot32::graphics::Color)0, // Transparent
        (pixelroot32::graphics::Color)1, // blue
        (pixelroot32::graphics::Color)2, // blue
        (pixelroot32::graphics::Color)3, // blue
        (pixelroot32::graphics::Color)4, // green
        (pixelroot32::graphics::Color)5, // blue
        (pixelroot32::graphics::Color)6, // orange
        (pixelroot32::graphics::Color)7, // red
        (pixelroot32::graphics::Color)8, // purple
        (pixelroot32::graphics::Color)9, // peach/salmon
        (pixelroot32::graphics::Color)10, // green
        (pixelroot32::graphics::Color)11, // purple
        (pixelroot32::graphics::Color)12, // peach/salmon
        (pixelroot32::graphics::Color)13, // peach/salmon
        (pixelroot32::graphics::Color)14, // white
        (pixelroot32::graphics::Color)15, // peach/salmon
    };

    using namespace pixelroot32::physics;

    // --- Tile Dimensions ---
    static const uint8_t TILE_SIZE = 16;
    static const uint8_t MAP_WIDTH = 30;
    static const uint8_t MAP_HEIGHT = 30;

    // --- Player Spawn (tile coords; Y = feet row) ---
    static const uint16_t SPAWN_TILE_X = 7;
    static const uint16_t SPAWN_TILE_Y = 8;

#if PIXELROOT32_ENABLE_GAMEPLAY_ROOM
    // --- Room Metadata (tile coords) ---
    static const pixelroot32::gameplay::RoomData ROOMSCENE_MAIN_SCENE_ROOMS[] = {
        // originCol, originRow, cols, rows, { Up, Down, Left, Right }
        {  0, 0, 15, 15, { 0xFFFF,      2, 0xFFFF,      1 } },
        { 15, 0, 15, 15, { 0xFFFF,      3,      0, 0xFFFF } },
        {  0, 15, 15, 15, {      0, 0xFFFF, 0xFFFF,      3 } },
        { 15, 15, 15, 15, {      1, 0xFFFF,      2, 0xFFFF } },
    };

    static const pixelroot32::gameplay::RoomLayer ROOMSCENE_MAIN_SCENE_ROOM_LAYER = {
        ROOMSCENE_MAIN_SCENE_ROOMS,  // rooms
        4,                           // roomCount
        16,                          // tileWidth
        16                           // tileHeight
    };

#endif // PIXELROOT32_ENABLE_GAMEPLAY_ROOM

    // --- Layer Definitions ---
    extern pixelroot32::graphics::TileMap4bpp background;
    extern pixelroot32::graphics::TileMap4bpp items;
    extern pixelroot32::graphics::TileMap4bpp details;

    /**
     * Initializes the scene components.
     * Call this once before drawing in the render loop.
     */
    void init();

    // ============================================================================
    // PixelRoot32 Tile Behavior Layer (ESP32 Optimization)
    // Generated by PixelRoot32 Tilemap Editor
    // ============================================================================

    // --- Behavior Layer: Background (30x30) ---

    /**
     * Dense behavior data array for layer "Background".
     * Each byte contains TileFlags combination for the corresponding tile.
     * 0 = TILE_NONE (no behavior)
     */
    static const uint8_t TILE_BEHAVIOR_LAYER_BACKGROUND[] PIXELROOT32_SCENE_FLASH_ATTR = {
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 0
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 1
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 2
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 3
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 4
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 5
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 6
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 7
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 8
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 9
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 10
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 11
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 12
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 13
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 14
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 15
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 16
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 17
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 18
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 19
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 20
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 21
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 22
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 23
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 24
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 25
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 26
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 27
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 28
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0  // Row 29
    };

    // --- Behavior Layer: Items (30x30) ---

    /**
     * Dense behavior data array for layer "Items".
     * Each byte contains TileFlags combination for the corresponding tile.
     * 0 = TILE_NONE (no behavior)
     */
    static const uint8_t TILE_BEHAVIOR_LAYER_ITEMS[] PIXELROOT32_SCENE_FLASH_ATTR = {
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 0
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 1
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 2
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 3
        0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 4
        0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 5
        0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 6
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,  // Row 7
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,  // Row 8
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 9
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 10
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 11
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 12
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 13
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 14
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 15
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 16
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 17
        0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 18
        0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,  // Row 19
        0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,  // Row 20
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,  // Row 21
        0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,  // Row 22
        0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,  // Row 23
        0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0,  // Row 24
        0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,  // Row 25
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 26
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 27
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 28
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0  // Row 29
    };

    // --- Behavior Layer: Details (30x30) ---

    /**
     * Dense behavior data array for layer "Details".
     * Each byte contains TileFlags combination for the corresponding tile.
     * 0 = TILE_NONE (no behavior)
     */
    static const uint8_t TILE_BEHAVIOR_LAYER_DETAILS[] PIXELROOT32_SCENE_FLASH_ATTR = {
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 0
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 1
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 2
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 3
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 4
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 5
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 6
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 7
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 8
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 9
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 10
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 11
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 12
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 13
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 14
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 15
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 16
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 17
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 18
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 19
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 20
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 21
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 22
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 23
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 24
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 25
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 26
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 27
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  // Row 28
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0  // Row 29
    };

    // All behavior layers
    static const TileBehaviorLayer behavior_layers[] = {
        { TILE_BEHAVIOR_LAYER_BACKGROUND, 30, 30 },         { TILE_BEHAVIOR_LAYER_ITEMS, 30, 30 },         { TILE_BEHAVIOR_LAYER_DETAILS, 30, 30 }    };

    static const uint8_t NUM_BEHAVIOR_LAYERS = 3;

    /**
     * Get TileFlags for a specific tile position in a behavior layer.
     * 
     * Args:
     *   layer_idx: Behavior layer index (0-based)
     *   x: X coordinate in tiles
     *   y: Y coordinate in tiles
     * 
     * Returns:
     *   TileFlags combination (0 = TILE_NONE if out of bounds)
     */
    inline uint8_t getTileFlags(uint8_t layer_idx, int x, int y) {
        if (layer_idx >= NUM_BEHAVIOR_LAYERS) {
            return 0; // TILE_NONE
        }
        
        const TileBehaviorLayer& layer = behavior_layers[layer_idx];
        if (x < 0 || x >= (int)layer.width || y < 0 || y >= (int)layer.height) {
            return 0; // TILE_NONE
        }
        
        return layer.data[y * layer.width + x];
    }

    // ============================================================================
    // PixelRoot32 Tile Animation System
    // ============================================================================

    // Animation definitions for layer: Details
    static const uint8_t DETAILS_TILE_ANIMATION_COUNT = 0;

    pixelroot32::graphics::TileAnimationManager& getDetailsAnimManager();
    // Legacy compatibility accessor - aliases Details.
    pixelroot32::graphics::TileAnimationManager& getAnimManager();

} // namespace roomscreen::main_scene

#endif // ROOMSCREEN_MAIN_SCENE_H
