#pragma once

#include "platforms/PlatformDefaults.h"

#if PIXELROOT32_ENABLE_GAMEPLAY_ROOM

#include "gameplay/RoomLayout.h"

/**
 * PixelRoot32 Exported Room Layer: RoomScreen
 * Generated by PixelRoot32 Tilemap Editor
 *
 * Hand-written here to stand in for the editor's output until the room
 * metadata emitter ships. The shape is the contract, not the provenance:
 * see docs/tools/tilemap-editor/technical-reference.md#room-metadata.
 *
 * Two 15x15 tile rooms side by side at 16 px/tile — room 0 spans world
 * x [0, 240], room 1 spans x [240, 480]. Both are one screen tall.
 */

namespace room_screen {

// --- Room Metadata ---
static const pixelroot32::gameplay::RoomData ROOM_SCREEN_ROOMS[] = {
    // originCol, originRow, cols, rows, { Up, Down, Left, Right }
    {  0, 0, 15, 15, { 0xFFFF, 0xFFFF, 0xFFFF,      1 } },
    { 15, 0, 15, 15, { 0xFFFF, 0xFFFF,      0, 0xFFFF } },
};

static const pixelroot32::gameplay::RoomLayer ROOM_SCREEN_ROOM_LAYER = {
    ROOM_SCREEN_ROOMS,  // rooms
    2,                  // roomCount
    16,                 // tileWidth
    16                  // tileHeight
};

} // namespace room_screen

#endif // PIXELROOT32_ENABLE_GAMEPLAY_ROOM
