// Generated by the legend_of_clone asset exporter - DO NOT EDIT BY HAND.
//
// The exporter and its character-art source are not versioned; see this
// example's README for what they are and where they live. Edit the art there
// and re-export - hand edits here are lost on the next run.
//
// Engine: PixelRoot32
// Mode: 4bpp

#ifndef CLONE_DUNGEON_TILEMAP_H
#define CLONE_DUNGEON_TILEMAP_H

#include "platforms/PlatformDefaults.h"

#ifdef PIXELROOT32_ENABLE_4BPP_SPRITES

#include "graphics/Renderer.h"
#include <stdint.h>

/**
 * @file DungeonTileMap.h
 * @brief Four dungeon rooms on the same 2x2 grid the overworld uses.
 */

namespace legend_of_clone {
namespace dungeon {

    // --- Dimensions ---
    static const uint8_t  TILE_SIZE  = 16;
    static const uint8_t  MAP_WIDTH  = 30;
    static const uint8_t  MAP_HEIGHT = 22;
    static const uint16_t TILE_COUNT = 4;

    // --- Tile ids ---
    // 1-based: drawTileMap skips index 0, so slot 0 is reserved and never drawn.

    /** Reserved slot 0. Never drawn - drawTileMap skips index 0. */
    static const uint8_t TILE_EMPTY = 0;

    /**
     * Floor: flat black.
     *
     * Featureless on purpose. Dungeon floors in the original are black, and the
     * room reads as an interior because of the wall that frames it, not because
     * the floor is textured.
     */
    static const uint8_t TILE_FLOOR = 1;

    /**
     * Wall: large blue blocks in offset courses, so a two-tile-thick wall reads
     * as masonry rather than as a grid of stamps.
     */
    static const uint8_t TILE_WALL = 2;

    /**
     * Stairs out of the dungeon. Grey treads on the black floor. WALKABLE -
     * stepping onto them leaves the dungeon.
     */
    static const uint8_t TILE_STAIRS = 3;

    /**
     * @brief Per-tile collision, indexed by tile id.
     *
     * Collision is a property of the tile here, not of a separate layer, so it
     * is exported alongside the tileset and cannot drift away from the art.
     */
    extern const bool TILE_SOLID[TILE_COUNT];

    /** The drawable layer. Valid only after init(). */
    extern pixelroot32::graphics::TileMap4bpp terrain;

    /**
     * @brief Wires the descriptors above to the exported data.
     *
     * Idempotent, and cheap: it assigns pointers, it does not copy pixels.
     * Call once before drawing.
     */
    void init();

} // namespace dungeon
} // namespace legend_of_clone

#endif // PIXELROOT32_ENABLE_4BPP_SPRITES

#endif // CLONE_DUNGEON_TILEMAP_H
