// Generated by the legend_of_clone asset exporter - DO NOT EDIT BY HAND.
//
// The exporter and its character-art source are not versioned; see this
// example's README for what they are and where they live. Edit the art there
// and re-export - hand edits here are lost on the next run.
//
// Engine: PixelRoot32
// Mode: 4bpp

#ifndef CLONE_OVERWORLD_TILEMAP_H
#define CLONE_OVERWORLD_TILEMAP_H

#include "platforms/PlatformDefaults.h"

#ifdef PIXELROOT32_ENABLE_4BPP_SPRITES

#include "graphics/Renderer.h"
#include <stdint.h>

/**
 * @file OverworldTileMap.h
 * @brief Four adjacent overworld screens, 15x11 tiles each, laid out 2x2.
 */

namespace legend_of_clone {
namespace overworld {

    // --- Dimensions ---
    static const uint8_t  TILE_SIZE  = 16;
    static const uint8_t  MAP_WIDTH  = 30;
    static const uint8_t  MAP_HEIGHT = 22;
    static const uint16_t TILE_COUNT = 7;

    // --- Tile ids ---
    // 1-based: drawTileMap skips index 0, so slot 0 is reserved and never drawn.

    /** Reserved slot 0. Never drawn - drawTileMap skips index 0. */
    static const uint8_t TILE_EMPTY = 0;

    /** Sand. Flat, like the NES original - the texture comes from what sits on it. */
    static const uint8_t TILE_GROUND = 1;

    /**
     * Walkable grass patch. A flat green block, sparsely flecked so a field of
     * them does not read as one solid slab.
     */
    static const uint8_t TILE_GRASS = 2;

    /**
     * The round bush scattered across the overworld. Blocking.
     * The navy bar beneath it is the drop shadow every NES overworld object casts.
     */
    static const uint8_t TILE_BUSH = 3;

    /**
     * Mountain face. Two browns in a masonry bond that tiles seamlessly, so a
     * block of these reads as one mass rather than a grid of stamps.
     */
    static const uint8_t TILE_ROCK = 4;

    /**
     * Cave mouth: solid black. WALKABLE - stepping onto it enters the dungeon.
     *
     * Deliberately featureless. The opening is always laid out as a 2x2 block
     * cut into a mountain, so the arch is drawn by the rock *around* it -
     * exactly how the NES does it. A tile with its own arch would repeat four
     * times.
     */
    static const uint8_t TILE_CAVE = 5;

    /**
     * Forest. One tree fills the whole tile - crown, then trunk.
     *
     * An earlier version packed two 8px trees per tile. At this scale that read
     * as a green field speckled with black rather than as woods: the gaps were
     * the same size as the foliage. One tree per tile puts the black where a
     * forest actually has it, in the wedges between neighbouring crowns.
     */
    static const uint8_t TILE_TREE = 6;

    /**
     * @brief Per-tile collision, indexed by tile id.
     *
     * Collision is a property of the tile here, not of a separate layer, so it
     * is exported alongside the tileset and cannot drift away from the art.
     */
    extern const bool TILE_SOLID[TILE_COUNT];

    /** The drawable layer. Valid only after init(). */
    extern pixelroot32::graphics::TileMap4bpp terrain;

    /**
     * @brief Wires the descriptors above to the exported data.
     *
     * Idempotent, and cheap: it assigns pointers, it does not copy pixels.
     * Call once before drawing.
     */
    void init();

} // namespace overworld
} // namespace legend_of_clone

#endif // PIXELROOT32_ENABLE_4BPP_SPRITES

#endif // CLONE_OVERWORLD_TILEMAP_H
