// Generated by the legend_of_clone asset exporter - DO NOT EDIT BY HAND.
//
// The exporter and its character-art source are not versioned; see this
// example's README for what they are and where they live. Edit the art there
// and re-export - hand edits here are lost on the next run.
//
// Engine: PixelRoot32
// Mode: 4bpp

#ifndef CLONE_PLAYER_SPRITES_H
#define CLONE_PLAYER_SPRITES_H

#include "platforms/PlatformDefaults.h"

#ifdef PIXELROOT32_ENABLE_4BPP_SPRITES

#include "graphics/Renderer.h"
#include "assets/PlayerPalette.h"
#include <stdint.h>

/**
 * @file PlayerSprites.h
 * @brief The hero: 4 bitmaps covering four directions and a
 *        two-frame walk cycle.
 *
 * | Direction | Frame 0       | Frame 1                       |
 * |-----------|---------------|-------------------------------|
 * | South     | PLAYER_DOWN   | PLAYER_DOWN mirrored          |
 * | North     | PLAYER_UP     | PLAYER_UP mirrored            |
 * | East      | PLAYER_SIDE_A | PLAYER_SIDE_B - a real bitmap |
 * | West      | east, mirrored                                |
 *
 * Which frames are mirrors and which are not is MEASURED, not assumed - run
 * check_sprites.py. The two vertical directions mirror because the hero holds
 * nothing in either hand, so a flip has no held object to teleport across his
 * body; the side pair cannot, because mirroring a side-on pose turns him
 * around instead of animating him.
 *
 * There is no black in him. His outline, hair, boots and belt are one brown,
 * and with the tunic green and his skin that is three colors and a hole - one
 * NES sprite palette exactly, which is the entire budget a 1986 cartridge had
 * for a hero. Outlining a sprite in black is the fastest way to make it stop
 * reading as an 8-bit character.
 */

namespace legend_of_clone {

    static const uint8_t PLAYER_WIDTH  = 16;
    static const uint8_t PLAYER_HEIGHT = 16;

    /**
     * Facing south. Frame 1 is this mirrored.
     *
     * Everything above the boots is left-right symmetric, so the mirror moves
     * only the feet - which is the whole animation.
     */
    static const uint16_t PLAYER_DOWN_4BPP[] = {
        0x0000, 0x2220, 0x0222, 0x0000,
        0x0000, 0x2222, 0x2222, 0x0000,
        0x0100, 0x3332, 0x2333, 0x0010,
        0x0100, 0x3333, 0x3333, 0x0010,
        0x1100, 0x1213, 0x3121, 0x0011,
        0x1100, 0x1313, 0x3131, 0x0011,
        0x1000, 0x1111, 0x1111, 0x0001,
        0x2000, 0x3112, 0x2113, 0x0002,
        0x3300, 0x3332, 0x2333, 0x0033,
        0x3300, 0x3322, 0x2233, 0x0033,
        0x1300, 0x3222, 0x2223, 0x0031,
        0x1300, 0x2222, 0x2222, 0x0031,
        0x1300, 0x3333, 0x3333, 0x0031,
        0x3000, 0x2222, 0x2222, 0x0003,
        0x3000, 0x0033, 0x3000, 0x0003,
        0x3000, 0x0003, 0x3000, 0x0033,
    };

    /** Facing east, frame 0. Mirrored for west. */
    static const uint16_t PLAYER_SIDE_A_4BPP[] = {
        0x0000, 0x2220, 0x0002, 0x0000,
        0x2000, 0x2222, 0x3333, 0x0000,
        0x2220, 0x3221, 0x3333, 0x0003,
        0x2222, 0x3311, 0x3333, 0x0000,
        0x2202, 0x3111, 0x1211, 0x0000,
        0x3200, 0x3113, 0x1311, 0x0001,
        0x3000, 0x1133, 0x1111, 0x0000,
        0x0000, 0x2222, 0x1111, 0x0000,
        0x2300, 0x2222, 0x3322, 0x0003,
        0x3330, 0x1112, 0x3222, 0x0003,
        0x3330, 0x1113, 0x3222, 0x0003,
        0x3330, 0x2113, 0x0322, 0x0000,
        0x3200, 0x3223, 0x0333, 0x0000,
        0x2220, 0x2222, 0x0222, 0x0000,
        0x0000, 0x3333, 0x0000, 0x0000,
        0x0000, 0x3333, 0x0003, 0x0000,
    };

    /**
     * Facing east, frame 1. A pixel lower than frame 0 - the walk bob.
     *
     * A real bitmap, not a mirror: mirroring a side-on pose turns him around
     * rather than animating him. Measured at 146 differing pixels against the
     * mirror of frame 0, where the front pair measures 0.
     */
    static const uint16_t PLAYER_SIDE_B_4BPP[] = {
        0x0000, 0x0000, 0x0000, 0x0000,
        0x0000, 0x2220, 0x0002, 0x0000,
        0x2000, 0x2222, 0x3333, 0x0000,
        0x2220, 0x3221, 0x3333, 0x0003,
        0x2222, 0x3311, 0x3333, 0x0000,
        0x2202, 0x3111, 0x1211, 0x0000,
        0x3200, 0x3113, 0x1311, 0x0001,
        0x3000, 0x1133, 0x1111, 0x0000,
        0x0000, 0x2222, 0x1111, 0x0000,
        0x3200, 0x1223, 0x3311, 0x0000,
        0x3300, 0x1333, 0x3211, 0x0000,
        0x3320, 0x1333, 0x3221, 0x0000,
        0x3220, 0x2333, 0x0322, 0x0000,
        0x2233, 0x3222, 0x2333, 0x0000,
        0x2333, 0x2222, 0x3222, 0x0003,
        0x3330, 0x0000, 0x3330, 0x0000,
    };

    /**
     * Facing north. Frame 1 is this mirrored.
     *
     * The feet are deliberately off-centre. An earlier version of this sprite
     * was perfectly symmetric, which made the mirror a visual no-op and the
     * walk cycle invisible - it looked like a bug in the timer. Four pixels of
     * asymmetry is all it takes; check_sprites.py reports the count.
     */
    static const uint16_t PLAYER_UP_4BPP[] = {
        0x0000, 0x2220, 0x0222, 0x0000,
        0x0000, 0x2222, 0x2222, 0x0000,
        0x0100, 0x2222, 0x2222, 0x0010,
        0x2100, 0x2222, 0x2222, 0x0012,
        0x3100, 0x2222, 0x2222, 0x0013,
        0x1100, 0x2233, 0x3322, 0x0011,
        0x1000, 0x2333, 0x3332, 0x0001,
        0x2000, 0x2222, 0x2222, 0x0002,
        0x3300, 0x2222, 0x2222, 0x0033,
        0x3300, 0x3332, 0x2333, 0x0033,
        0x1300, 0x2222, 0x2222, 0x0031,
        0x1300, 0x2222, 0x2222, 0x0031,
        0x1300, 0x3333, 0x3333, 0x0031,
        0x3000, 0x2222, 0x2222, 0x0003,
        0x3000, 0x0033, 0x3000, 0x0003,
        0x3000, 0x0003, 0x3000, 0x0033,
    };

    /**
     * @brief The five bitmaps as engine sprite descriptors.
     *
     * Index with PlayerFrame below rather than by number.
     */
    static const pixelroot32::graphics::Sprite4bpp PLAYER_FRAMES[] = {
        { reinterpret_cast<const uint8_t*>(PLAYER_DOWN_4BPP), PLAYER_PALETTE_MAPPING, PLAYER_WIDTH, PLAYER_HEIGHT, 16 },
        { reinterpret_cast<const uint8_t*>(PLAYER_SIDE_A_4BPP), PLAYER_PALETTE_MAPPING, PLAYER_WIDTH, PLAYER_HEIGHT, 16 },
        { reinterpret_cast<const uint8_t*>(PLAYER_SIDE_B_4BPP), PLAYER_PALETTE_MAPPING, PLAYER_WIDTH, PLAYER_HEIGHT, 16 },
        { reinterpret_cast<const uint8_t*>(PLAYER_UP_4BPP), PLAYER_PALETTE_MAPPING, PLAYER_WIDTH, PLAYER_HEIGHT, 16 },
    };

    enum PlayerFrame : uint8_t {
        PLAYER_DOWN = 0,
        PLAYER_SIDE_A = 1,
        PLAYER_SIDE_B = 2,
        PLAYER_UP = 3,
    };

} // namespace legend_of_clone

#endif // PIXELROOT32_ENABLE_4BPP_SPRITES

#endif // CLONE_PLAYER_SPRITES_H
