// Generated by the legend_of_clone asset exporter - DO NOT EDIT BY HAND.
//
// The exporter and its character-art source are not versioned; see this
// example's README for what they are and where they live. Edit the art there
// and re-export - hand edits here are lost on the next run.
//
// Engine: PixelRoot32
// Mode: 4bpp

#ifndef CLONE_PLAYER_PALETTE_H
#define CLONE_PLAYER_PALETTE_H

#include "graphics/Renderer.h"
#include <stdint.h>

/**
 * @file PlayerPalette.h
 * @brief The RGB565 colors Link renders with.
 *
 * Installed with setSpriteCustomPalette(). Separate from the tilemap palette
 * because dual palette mode gives sprites their own 16 slots - so the world
 * and the hero are not competing for the same table.
 *
 * Three colors and a hole: exactly one NES sprite palette, which is the whole
 * budget the 1986 cartridge had for its hero.
 */

namespace legend_of_clone {

    // --- RGB565 by engine Color slot ---
    // Indexed by Color, NOT by 4bpp pixel value. Every color sits in its
    // conventional slot so Color::White is still white and Color::Red is still
    // red for anything that names a color instead of indexing art.
    static const uint16_t PLAYER_SPRITE_PALETTE_RGB565[16] = {
        0x0000, //  0 Black - unused
        0xFFFF, //  1 White - text and error messages
        0x0000, //  2 Navy - unused
        0x0000, //  3 Blue - unused
        0xFCC7, //  4 Cyan  's'  #FC9838  Link's skin
        0x0000, //  5 DarkGreen - unused
        0x0000, //  6 Green - unused
        0x8682, //  7 LightGreen  'l'  #80D010  Link's tunic
        0x0000, //  8 Yellow - unused
        0x0000, //  9 Orange - unused
        0xCA61, // 10 LightRed  'h'  #C84C0C  Link's brown - outline, hair, boots, belt
        0xF9C0, // 11 Red - error text - must never resolve to black
        0x0000, // 12 DarkRed - unused
        0x6A3F, // 13 Purple - unused
        0xBDDF, // 14 Magenta - unused
        0xBDF7, // 15 Gray - dimmed text
    };

    // --- 4bpp pixel value to engine Color slot ---
    // The blitter reads sprite.palette[pixelValue] as a Color and resolves that
    // slot against the table above. Entry 0 is never read: pixel value 0 is a
    // hole, which is why black has to live at pixel value 1 and not at 0.
    static const pixelroot32::graphics::Color PLAYER_PALETTE_MAPPING[16] = {
        pixelroot32::graphics::Color::Black, //  0 transparent - never read
        pixelroot32::graphics::Color::Cyan, //  1 's' -> Cyan
        pixelroot32::graphics::Color::LightGreen, //  2 'l' -> LightGreen
        pixelroot32::graphics::Color::LightRed, //  3 'h' -> LightRed
        pixelroot32::graphics::Color::Black, //  4 unused
        pixelroot32::graphics::Color::Black, //  5 unused
        pixelroot32::graphics::Color::Black, //  6 unused
        pixelroot32::graphics::Color::Black, //  7 unused
        pixelroot32::graphics::Color::Black, //  8 unused
        pixelroot32::graphics::Color::Black, //  9 unused
        pixelroot32::graphics::Color::Black, // 10 unused
        pixelroot32::graphics::Color::Black, // 11 unused
        pixelroot32::graphics::Color::Black, // 12 unused
        pixelroot32::graphics::Color::Black, // 13 unused
        pixelroot32::graphics::Color::Black, // 14 unused
        pixelroot32::graphics::Color::Black, // 15 unused
    };

} // namespace legend_of_clone

#endif // CLONE_PLAYER_PALETTE_H
